### ISSUE TITLE
[Mapvote] "GetMapsFromMapCycle" option set to false seems not to work

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#427]
It seems like setting "GetMapsFromMapCycle" to false has no effect on the vote list at all.

**Comment by Person8880** [comment]
It definitely has the desired effect now. However I've also changed how it works slightly.

Before you'd get all the information about each map for things like min/max counts from the map cycle entry. Now if you use `"GetMapsFromMapCycle": false` it'll use whatever's in the `"Maps": {}` table as the map's settings instead. This is to allow you to use maps that aren't in the cycle but you want to be vote-able and with min/max/round/time limit settings.

There was also a bug that's been in forever where the round/time limits for a map would just use the last time/round limit it found in the map cycle. I'm not sure how I never saw that before!
