### ISSUE TITLE
Child plug-ins get auto-loaded by their parent plug-in

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#436]
Stumbled over this issue while working on one of my plug-ins.

A easy way to reproduce this issue is to disable the commbans plug-in in the base config while having the ban plug-in enabled.

The commbans plug-in will still load up even though it has been disabled.

**Comment by Person8880** [comment]
They weren't even being loaded properly, just they were inheriting the "Enabled" flag. Fixed now.
