### ISSUE TITLE
[VoteRandom] Allow player to pick team preferences

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#461]
One of the main reason people chose to use the NS2 FET over Shuffle is that Shuffle doesn't allow you to pick one team you would prefer to play. 

And after being forced to play marines three times in a row when you originally wanted to play aliens just gets annoying.

This lead to a increasing number of players disconnecting after a Shuffle. 

Therefor it might be nice to add another optimization round to the shuffle method which swaps almost equally skilled players if their team preferences would be fulfilled that way. 

Of course then there has to way to set a preference for players. This could be done either through the shine vote menu or by taking the teams the player were in before a shuffle kicked in as preferences.

**Comment by Person8880** [comment]
Being on a team when the shuffle runs now marks players as preferring their current team, and forces the shuffle algorithm to ignore them on the first pass.
