### ISSUE TITLE
Shuffle is not working  with specs

### ISSUE THREAD

**Issue by myrljus** [Person8880/Shine#463]
On Woozas HamsterWheel we have a setup with 32 players and 10 specs, and shuffling sometimes makes the teams overrun the team size limit. Sometimes we end up with 19 vs 16 and variations there of. this happens after a voted shuffle or sh_enablerandom

**Comment by Person8880** [comment]
Are you using a plugin that enforces team sizes?

**Comment by myrljus** [comment]
i think this:https://github.com/GhoulofGSG9/Shine-Epsilon/wiki/Enforce-Team-Sizes

**Comment by Person8880** [comment]
That plugin should be responsible for maintaining the team counts, rather than the shuffle. I'd bring it up as an issue there instead.

**Comment by myrljus** [comment]
ok thx
