### ISSUE TITLE
Is it possible to make a % limit on maps?

### ISSUE THREAD

**Issue by DCMAKER** [Person8880/Shine#467]
Is there a way to add a feature so you can limit what percentage a map can be played on a server? I know you can limit how long til the map can be replayed but can you limit a map to let us say 8% of total times being played?

**Comment by Person8880** [comment]
There is a way to [set how likely a map is to appear in a vote](https://github.com/Person8880/Shine/wiki/Map-Vote#making-maps-have-different-chances-to-be-picked-for-a-vote), is that the sort of thing you're after?

**Comment by GhoulofGSG9** [comment]
I guess he want that shine tracks how often each map got played and starts filtering out maps once the have been played more than x % of the tracked time.

**Comment by Person8880** [comment]
Well, if you set a map to be 10% chance of showing up, then the maximum expected amount of times it would be played (assuming every time it appears it is chosen, likely not the case) would be 10% of the total. Not quite a guarantee, but pretty much the same thing.

**Comment by DCMAKER** [comment]
currently you can only set the number of rounds before the map can be replayed, which is better then nothing but it still ends up making servers play the same 5 maps continuously instead of getting some real variety.

**Comment by DCMAKER** [comment]
http://www.gametracker.com/server_info/45.35.1.10:27015/

here is a server for an example. You can see how often a map is played and it typically is the same 5 maps over and over. The only feature that prevents a single map from being played again and again is by increasing the delay of X map changes til it pops up again but that affects every map and doesn't really solve the problem of repetitive play of the same 4 stock maps, which kills the server or game for people who have played for 100s of hours.

**Comment by Person8880** [comment]
This is now addressed by e84571144399a9de3089c8627e0a55df01cbd6d0. Essentially, if you want to limit the percentage of the total maps played for a specific map, then the map should look something like this in the MapCycle.json file:

```json
{ "map": "ns2_tram", "percent": 8 }
```
