### ISSUE TITLE
[Question] Notify all Admins/Mods

### ISSUE THREAD

**Issue by Fogger** [Person8880/Shine#483]
Is there something like `NotifyDualColour()` that only Admins or Mods can see?

or something I can put in the first arg instead of `player`?

**Comment by Person8880** [comment]
The first argument doesn't have to be a single player. You can pass a table of players/clients and it will send to all of them.

For example:
```lua
-- Send to connected clients in the group "YourAdminGroup"
Shine:NotifyDualColour( Shine:GetClientsByGroup( "YourAdminGroup" ), 255, 255, 0, "(To Admins)", 255, 255, 255, "Hello admins!" )
-- Send to connected clients with access to "sh_youraccessflag"
Shine:NotifyDualColour( Shine:GetClientsWithAccess( "sh_youraccessflag" ), 255, 255, 0, "(To Admins)", 255, 255, 255, "Hello admins!" )
```

Hope that answers your question.

**Comment by Fogger** [comment]
Awesome!  Thank you.
