### ISSUE TITLE
Default BWLimit was increased to 50 kb/s with build 278

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#484]
The default limit of the base command plug-in should be adjusted as well.

**Comment by Person8880** [comment]
Default in the config is now 50.

**Comment by GhoulofGSG9** [comment]
I had something more like this in mind: https://github.com/GhoulofGSG9/Shine/commit/ebe64937cbbbdc2691a1bcea419caff9c059e91f

The issue with just increasing the default to 50 would be that it doesn't upgrade the value for servers which run previous to this change.

**Comment by Person8880** [comment]
I'm not overly keen on these one-off config switches. I think if anything, a simple startup warning for when the bandwidth limit is less than the default should be enough.

**Comment by GhoulofGSG9** [comment]
The warning should also do it.
