### ISSUE TITLE
AFKKick will kick coms out of the game

### ISSUE THREAD

**Issue by SamDaMan1** [Person8880/Shine#495]
Copy of my config:
{
    "IgnoreSpectators":true,
    "Delay":1,
    "MoveToSpectateOnWarn":false,
    "WarnTime":2,
    "MinPlayers":16,
    "OnlyCheckOnStarted":true,
    "WarnMinPlayers":15,
    "KickTime":10,
    "Warn":true,
    "KickOnConnect":true,
    "MoveToReadyRoomOnWarn":true
  }

Essentially it seems as if the AFKKick can not tell the difference between a commander and an ordinary player. Several times now I have been kicked from my own server and seen other coms kicked even though they were active.

Steps to reproduce:
Activate AFKKick,
Set it to kick min players 1,
Jump on a private server,
Get in com chair,
Get kicked.

I am not sure if it will work when you are alone but it happens for me when other players are playing on the server.

**Comment by Person8880** [comment]
A few things to check:
- Is the vanilla AFK check active? As far as I know it will happily kick spectators and commanders with quite a bit less care. It's the `auto_kick_afk_time` setting in `ServerConfig.json`, should be set to 0 to disable it.
- Are you actually moving around, building structures etc? It should be resetting the time every time a commander moves their view, starts constructing something, gives an order and performs a "tech tree action".

**Comment by SamDaMan1** [comment]
Here is a copy of my ServerConfig:

{
  "tags":["rookie"],
  "settings":{
    "rookie_friendly":true,
    "force_even_teams_on_join":true,
    "enabledyndns":false,
    "auto_team_balance":{
      "enabled_after_seconds":10,
      "enabled":true,
      "enabled_on_unbalance_amount":2
    },
    "use_own_consistency_config":false,
    "season_month":0,
    "dyndns":"",
    "end_round_on_team_unbalance_check_after_time":300,
    "jit_maxmcode":36000,
    "auto_kick_afk_capacity":0.5,
    "mod_backup_servers":[],
    "jit_maxtrace":20000,
    "voting":{
      "votekickbantime":30,
      "votechangemap":false,
      "votingforceeventeams":false,
      "voteresetgame":true,
      "votekickplayer":true,
      "voterandomizerr":true
    },
    "pregamealltalk":true,
    "mod_backup_before_steam":false,
    "alltalk":false,
    "auto_kick_afk_time":0,
    "season":"",
    "consistency_enabled":true,
    "end_round_on_team_unbalance_after_warning_time":30,
    "hiveranking":true,
    "end_round_on_team_unbalance":0.4
  }
}


And yea even when building items, dropping medkits, talking over microphone, typing, etc.

**Comment by Person8880** [comment]
As far as I can see, when I place structures, medpacks etc. it's resetting the time. Text chat and voice chat also reset it. Moving the camera resets it too. The only thing that doesn't reset it is giving an order, which I can add. But it should be very difficult as it is to get kicked out for being AFK unless the commander's sat with their view stationary all the time.

**Comment by Person8880** [comment]
Sorry, I see the problem now. Missed you were using `KickOnConnect`. It's kicking based on seconds when `KickTime` is minutes. I'll publish a fix for that now.

**Comment by SamDaMan1** [comment]
Aweee yeahhh! Awesome!

**Comment by Person8880** [comment]
Can I assume this is resolved now? It hasn't kicked anyone incorrectly since the update?

**Comment by SamDaMan1** [comment]
Yes, just tested with a full server and no one got kicked. Thanks for the fix :D
