### ISSUE TITLE
Account for Steam family sharing in the bans plugin

### ISSUE THREAD

**Issue by Person8880** [Person8880/Shine#501]
If provided a Steam API key and set to enable the family sharing check, the bans plugin should determine if a connecting player is family sharing with a banned user and if so, kick them when they've finished loading in. Can't kick them on connect because we can't (and don't want to) hold up the main thread waiting for a response.

The response should be cached in memory so that if the player attempts to connect again then no request to Steam is required, and they can be immediately rejected.

**Comment by GhoulofGSG9** [comment]
Not sure if you have seen this but you can fetch the needed data via the steam web api  ( https://lab.xpaw.me/steam_api_documentation.html#IPlayerService_IsPlayingSharedGame_v1 )
