### ISSUE TITLE
Is there any way to make adverts play in a random order?

### ISSUE THREAD

**Issue by SamDaMan1** [Person8880/Shine#503]
As the title says, can I change the adverts to display in a random order instead of it reading from top to bottom?

If so, does the random order make sure not to display the same advert more than once in a match?

If not, would you be willing to implement this? I am currently making tips new users can read in the chat box but I am afraid they may miss some.

**Comment by Person8880** [comment]
The currently published version doesn't have an option for this, but I've implemented it in 81a248d04338c346d576328441b6e9086bc32ac6 so the next update will have it.

**Comment by SamDaMan1** [comment]
Alright, thanks for the heads up!
