### ISSUE TITLE
Is there any way to balance the game without hive?

### ISSUE THREAD

**Issue by SamDaMan1** [Person8880/Shine#514]
Currently modded servers cannot get whitelisted for hive recording. A server that is not on the hive whitelist will get no stats tracked, at all. Rookies won't level up, no recording of KDR, no hive skill.

There are users who only play on the modded server as well, so they will become better and better at the game but they won't get balanced correctly due to no recordings.

What I am wondering is, is there some way to balance the teams for modded servers who aren't allowed access to hive skill or anytype of skill recording?

**Comment by Person8880** [comment]
At the moment, no. But I can add an option to use a locally stored set of stats instead, and make it gather them for players on your server over time. I can also make it start from the Hive values and go from there. It would be KDR or score/minute only though, as implementing the Hive system locally wouldn't go too well.

**Comment by SamDaMan1** [comment]
That would be amazing. There are so little modded servers because you just can't balance the games because you have no hive skill or anything to go off of.
 
If you need my help to test it or anything, just shoot me a msg. I will be happy to put it up on my server and let it run.

**Comment by SamDaMan1** [comment]
Also, is it possible to get rid of the rookie label on players that play on the server?

For example: A rookie comes and plays for several days straight, becomes good at the game, but is still labeled a rookie and still gets trash talked by other players.

Is there a way to make the rookie label disappear for players that have x amount of hours on the server or something similar to that?

**Comment by Person8880** [comment]
I would imagine removing the rookie label is fairly straightforward. I'll know for sure when I get time to work on it.

**Comment by SamDaMan1** [comment]
I should also mention about the rookie thing. After this latest patch rookies also can't get into the comm chair until level 3. So the removal of the rookie tag would also need to make it so they can comm.

**Comment by Person8880** [comment]
Rookie handling is (thankfully) all done through one flag on players, so everything that affects rookies will be dealt with when it disables their rookie flag.

**Comment by SamDaMan1** [comment]
Oh! that's good to hear.

**Comment by Person8880** [comment]
This is in the update I just pushed out. [See here for how to enable it.](https://github.com/Person8880/Shine/wiki/Vote-Random#local-file-stats)

**Comment by SamDaMan1** [comment]
How long would it take to achieve 7500 score? For example how much score does a person usually get in a full round? 

Also, does the Rookie Boundary change? So if I set it to Timeplayed will it use seconds or minutes?

Thank you so much for making this!

**Comment by Person8880** [comment]
If you set it to `PlayTime`, it'll be in seconds as that's what Hive tracks (and thus is inherited by the local stats). 7500 score matches the game's Hive level 3 requirement, as 7500 score = level 3.

**Comment by SamDaMan1** [comment]
Wow, so it is basically hive but just offline? That is pretty awesome!

**Comment by Person8880** [comment]
Almost. The only difference is that there's no "skill" value.

**Comment by SamDaMan1** [comment]
Alright so I should stay away from balance mode 5?

**Comment by Person8880** [comment]
Yes, as that'll just use Hive data. Either KDR (4) or score per minute (2) will work with the local stats.

**Comment by SamDaMan1** [comment]
Alright

**Comment by SamDaMan1** [comment]
Does it increase the Hive skill number that you see with NS2+?

**Comment by Person8880** [comment]
No. That's coming from the Hive system and needs the server to report skill levels to change.

**Comment by SamDaMan1** [comment]
Alright, Ill turn off the numbers then
