### ISSUE TITLE
Rookies cannot enter a chair, even if they are the last person alive.

### ISSUE THREAD

**Issue by akrigline** [Person8880/Shine#527]
When the Chair blocks rookies, it doesn't care if this could cost Marines the game. Any way to add a check to see if they're the last people alive, or else if there are no IPs? Either instance would be good to allow anyone into the chair.

**Comment by Person8880** [comment]
Is this not a game bug? I could still "fix" it, but I think it should really be fixed in the game itself.

**Comment by akrigline** [comment]
I thought it was because of shine's server side option to prevent rookies from commanding. But I'm not certain.

**Comment by Person8880** [comment]
Maybe thinking of the `norookies` plugin under [Epsilon](https://github.com/GhoulofGSG9/Shine-Epsilon)? That's not part of the main mod. I know there's also a block in the game code itself against rookies entering the commander chair.

**Comment by akrigline** [comment]
Ahh, probably. Also forgot that they stopped letting greens command flat out. Will have to take this higher. Apologies.
