### ISSUE TITLE
Need a way to ban by IP address

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#545]
We need a way to ban by IP address.
Way too many smurfs, trolls, etc.

**Comment by Person8880** [comment]
IP addresses are not a reliable way to ban players at all. Most, if not all consumer grade ISPs will not allocate a static IP address, and thus a user banned by IP simply has to trigger their IP to change (often as simple as resetting their router/modem) and then the ban is lost.

If you're getting "smurf" accounts, are they using family sharing? You can set the bans plugin to check for and prevent players playing via family sharing where the account sharing is banned. All you need to do is set:

```json
"APIKeys": {
    "Steam": "<your API key>"
}
```
in `BaseConfig.json` and then `CheckFamilySharing = true` in `Bans.json`.

Regardless, an IP address ban is not the answer.

**Comment by Rusty01** [comment]
The problem with that is I do have legitmate people using family sharing - ie husbands and wives etc.
I know that ip addresses are not the perfect solution, but it'll help quite a bit.   There's a ton of people smurfing and the logs all show the same IP's.  It would be very helpful.

**Comment by Person8880** [comment]
The family sharing settings only kick out family sharing players _when the account lending the game is banned_. Legitimate uses of family sharing are unaffected.
