### ISSUE TITLE
afk-kick

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#547]
When player is AFK - option is to put the player into the RR at the same time as they are warned.
I would like there to be a 30 second delay between getting the warning for being AFK and actually being placed into the readyroom - or kicked.   

I would also like a chime or something to play if possible please.

Thanks!

**Comment by Person8880** [comment]
I should be able to add an extra delay setting, and make their task bar icon for NS2 flash when they receive the warning (assuming they're alt-tabbed). I'm not sure if there's a suitable sound, but I'll have a look.

**Comment by Rusty01** [comment]
What about this old thing...
http://mrclan.com/fastdl/tfc/sound/misc/kickdababy.wav
:)
Thanks for looking at this!

**Comment by Person8880** [comment]
I ended up using one of the old hint sounds (the little boxes that turn into a tick when you do something). It seems to work well enough.

**Comment by Rusty01** [comment]
Ok great.
I really appreciate all your work Person8880.   Thank you so much!
Sorry for the repost on the shuffle issue.  I couldn't find it, so thought it never saved.  My bad,
I'll talk to Ghoul about the issue.    Thanks again for adding the warning before kick feature!
