### ISSUE TITLE
Hive elo restrictions being bypassed by shuffle

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#551]
If players don't meet the elo requirements - they are still able to play via shuffle.

**Comment by Person8880** [comment]
You already raised this and I already answered it [here](https://github.com/Person8880/Shine/issues/546). Please don't re-post it.

The shuffle plugin is **not** responsible for restrictions other plugins want to enforce. If another plugin wants to restrict by Hive skill, then it is responsible for removing players from the shuffling pool. The shuffle plugin already exposes an event explicitly for this purpose.
