### ISSUE TITLE
EqualsCanTarget is not working as intended

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#556]
I have lately changed my userconfig.json so that Players with the same immunity can't kick each other anymore. This affects the custom Groups as well as the Default Group.

Now here starts the Problem: Sometimes, People can't start kickvotes against each other but sometimes they can. I have no clue why. I have set in baseconfig.json this Option: "EqualsCanTarget":false,

Goal is that Players can only start kickvotes against Players with a lower immunity, not against Players at the same Level. 

I don't post my userconfig.json here but Person8880 should receive the file by creating this thread.

**Comment by Person8880** [comment]
As far as I can tell, there's nothing wrong with `EqualsCanTarget`. However, the user config file you sent me has a few syntax errors (some missing or extra commas mostly).
