### ISSUE TITLE
[Pregame] Team player number depending game start

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#560]
A user requested a pregame mode where the game waits for x players to join the teams before it starts with commanders.

**Comment by Wyqer** [comment]
Thanks for opening this issue after our discord talk.
Idea for this mode: Until X Players are on the server, the server will be in the pregame mode. In this state it should also block the game to start when both teams have commanders but the needed player count isn't reached.

**Comment by Person8880** [comment]
To clarify: should the players all be on playing teams to be considered, or is it purely the number of players on the server you want it to track?

**Comment by Wyqer** [comment]
X Players assigned to Teams
Not X player on the server

**Comment by Person8880** [comment]
Another question: if the game is counting down to start, should it abort the game start if the number of players on teams drops below the minimum again, or just allow the game to start anyway?

**Comment by Person8880** [comment]
This has been released in today's update. Set the pregame `Mode` option to `4` to use it, and change the `MinPlayers` setting to whatever you want the minimum player count to be.

It will not abort the game if the number of players on teams drops below that during the countdown at the moment, though that could be changed in the future.
