### ISSUE TITLE
Limit usage of sh_nominate

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#562]
Sometimes it happens that a player is using sh_nominate so many times that he is filling the mapvote only with maps from him. In rare cases it can hurt the server as there is some people with a negative attitude regarding custom maps.

I would like to see a option somewhere where server operators can set the amount of how many times a player can use sh_nominate maximal.

**Comment by Person8880** [comment]
Use the new `MaxNominationsPerPlayer` option in the mapvote plugin to limit nominations.
