### ISSUE TITLE
Ignore Server for "Play Now"

### ISSUE THREAD

**Issue by FloCola** [Person8880/Shine#567]
Hi, a switch to add the servertag "Ignore Play Now" would be nice.
thats what i have from remi: : 'Server.AddTag("ignore_playnow")'

**Comment by Person8880** [comment]
As a command, or a config option?

If a config option, you can set tags in `ServerConfig.json` under `"tags"`.

**Comment by FloCola** [comment]
As an option.
> remi: @SupaFred no you'd need to do it as a mod
> [17:20] remi: the param doesn't exist in the server config

Thats all i know about it

**Comment by Person8880** [comment]
Well, he's wrong.

With `"tags":["ignore_playnow"]` in `ServerConfig.json`, the tag is present:
```
table: 0x8d481c04 {
	[ 1 ] = "ignore_playnow"
	[ 2 ] = "shine"
	[ 3 ] = "ServerTickrate30"
	[ 4 ] = "tickrate_30"
	[ 5 ] = "R_S1"
	[ 6 ] = "P_S0"
	[ 7 ] = "custom_network_settings"
}
[19:49:56]Person8880 ran: local Tags = {} Server.GetTags(Tags) PrintTable(Tags)
```

**Comment by FloCola** [comment]
wow... thx i guess. 👍
