### ISSUE TITLE
Setting BlockTeams to False in VoteRandom.json does not allow players to spectate

### ISSUE THREAD

**Issue by ironhorse86** [Person8880/Shine#568]
If you set BlockTeams to False, players can swap between teams, idle in the readyroom.. but they cannot join spectators.

IgnoreSpectators handles moving players that are _already_ in spectators it seems? (haven't test that yet however, and if its not the case, it is not documented)

**Comment by Person8880** [comment]
I can't reproduce this. With `BlockTeams` on or off, I can join spectate if I am in the ready room.

`IgnoreSpectators` is only for preventing them from being moved out of spectate when a team shuffle occurs.
