### ISSUE TITLE
Conflicts with Infested Marines gamemode

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#574]
There are some conflicts between Shine and the new game mode modification Infested Marines (http://steamcommunity.com/sharedfiles/filedetails/?id=788946394):
- When a map vote starts half of the players are not moved to the Ready Room.
- The game mode uses a new pattern based map cycle system which doesn't work with shine. Basically infest_veil will load ns2_veil with the game mode.
- Vote Surrender/Vote Random don't make much sense with this new game mode and should be disabled for it.

I will try to send pull request for those conflicts to either project where they are easier to resolve when i have time. 

There may be some more conflicts i am not aware of yet.

**Comment by Person8880** [comment]
> When a map vote starts half of the players are not moved to the Ready Room.

Looking at the code I don't see a reason for this? All players are on team 1, and the map vote just uses `Team:ForEachPlayer()` on that and team 2 to move them.

> The game mode uses a new pattern based map cycle system which doesn't work with shine. Basically infest_veil will load ns2_veil with the game mode.

Why doesn't it work? The UWE extension is hooking `Server.StartWorld`, so the map name is irrelevant before that. All Shine does is pass it into `MapCycle_ChangeMap` eventually, it doesn't care if it's a valid map or not.

> Vote Surrender/Vote Random don't make much sense with this new game mode and should be disabled for it.

This has now been addressed.

**Comment by GhoulofGSG9** [comment]
> > The game mode uses a new pattern based map cycle system which doesn't work with shine. Basically infest_veil will load ns2_veil with the game mode.

> Why doesn't it work? The UWE extension is hooking Server.StartWorld, so the map name is irrelevant before that. All Shine does is pass it into MapCycle_ChangeMap eventually, it doesn't care if it's a valid map or not.

I should have specified that a little more. What seems to not work is using the rounds and chance attributes in the map cycle. Map Vote still seems to look for the old ns2_map entry.

**Comment by Person8880** [comment]
Is this map cycle hack going to be permanent? I'm not sure I want to start checking map prefixes just for one gamemode.

**Comment by GhoulofGSG9** [comment]
Thank for your help.
I pushed fixes for the other conflicts to the infested mod as they indeed shouldn't be fixed by shine. `Shared.GetMapName()` now returns the map name with given prefix while the infested mod is running.
