### ISSUE TITLE
Vote Random Plugin - Local File Stats for multiple Servers

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#576]
I would like to know if it could be possible to support the "local hive" for multiple servers, not only one.

Right now I made a script that copies from one server to another but I can't really sync it.
If syncing is not possible, then I would like too se a function where other servers can at least read the hive score from another server.

**Comment by Wooza42** [comment]
To add on: Is it also possible that the plugin can calculate the skill formula since it already stores Information like playtime, kills etc. ?
In my eyes I don't see else a real advantage for non whitelisted hives, as Balance mode 2 (Score per minutes) and 4 (KDR based) are not really good for even teams.

**Comment by stickz** [comment]
You should be able to retrieve data from hive even though you can't contribute to hive in certain circumstances. This will be more accurate for balancing teams than any other shine method.

You'll just need something to account for fluctuations as more immediate games played won't be recorded. My suggestion would be to create a secondary equation for the client's accuracy that accounts for 30%. Then use hive skill for the other 70%. The problem with hive is it doesn't converge fast enough and not all servers are on. Shuffle could definitely be improved to detect and slightly offset certain imbalances.
