### ISSUE TITLE
Shine votes (and other types of votes really) should not take AFKs into account.

### ISSUE THREAD

**Issue by Laaas** [Person8880/Shine#584]
Votes like shuffling, etc. should not take AFKs into account.

**Comment by stickz** [comment]
That would be a very good idea to add a Boolean value to each type of vote; so the server operator can decide whether or not to make the pass requirement include AFKs.

**Comment by fazmond** [comment]
I second this !

**Comment by Person8880** [comment]
This will be in the next update, configurable per vote.

Map vote, shuffle and surrender will all have:
```json
"VoteSettings": {
    "AFKTimeInSeconds": 60,
    "ConsiderAFKPlayersInVotes": true
}
```
Changing `ConsiderAFKPlayersInVotes` to false will mean that AFK players no longer contribute to the total votes required.

Similarly, in the base commands plugin:
```json
"VoteSettings": {
      "VoteKickPlayer": {
          "AFKTimeInSeconds": 60,
          "ConsiderAFKPlayersInVotes": true
      }
}
```
Each entry's key refers to a vanilla vote name. You can add as many or as few as you want.
