### ISSUE TITLE
"__" string added to version number in json files possibly causing issues?

### ISSUE THREAD

**Issue by ironhorse86** [Person8880/Shine#586]
multiple json config files for plugins have had "__" added before "Version" and some custom plugins have had
"Version":"1.2"
"__Version":"1.2"
in a row.

an example :

{
    "AllowVoteWithMultipleBases":true,
    "MinPlayers":6,
    "PercentNeeded":0.65,
    "SkipSequence":false,
    "VoteDelay":2,
    "VoteTimeout":120,
    "__Version":"1.2"
  }

Deleting these two underscores doesn't remove it, it comes right back after a map change.

**Comment by Person8880** [comment]
`__Version` is an internal field to identify the corresponding plugin version a config was last checked against.

It's to allow for new plugin versions to alter the format and know how they need to transform older formats automatically without having to store loads of temporary variables.

You should leave it as-is. It's harmless and potentially necessary for future config updates to work.
