### ISSUE TITLE
Local Bans list mutliple servers same box

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#588]
I have 4 servers on the same machine that I would like to use the same bans.json
so that if a player becomes banned on 1 server then he will be banned on all of them 

I have made a hardlink to the file from server 1 to the other servers
only problem with that is that If I ban a player on server 1 it will write the ban list ok but if then a player is banned on server 2 before it can reload then ban list (ie on a map change) then it will lose the change server 1 has made and add the new ban from the cache that it had in its memory.

only way I can see this working across the servers is that if when a player is banned instead of just load the banlist at a map change it READS the bans.json then WRITES the bans.json in 1 go.

so server 1 bans a player it reads then writes, then when server 2 bans it again reads and writes keeping both changes each server has made.

I UNDERSTAND that a player wouldn't be banned on all servers the at the exact moment the ban has been made but at the moment the server reads the ban list again (either on a map change OR new ban)

Also it would be nice that the GET MORE BANS button would actually reload the ban list from the file again instead of trying to get fresh bans form a url if no url is present in the config.

I want this bans.json hosted on the machine and don't want to use the URL way thanx

**Comment by stickz** [comment]
I think what you're asking for is web configs on shine for bans? So when a person is banned, it will instead be updated in your web server and automatically read from for each of your multiple servers?

**Comment by Person8880** [comment]
This is impractical, and is the reason there's a HTTP request-driven solution in the first place.

Even if it did read the on-disk config before writing, you can still encounter race conditions where two servers read and write at the same moment, meaning one set of changes is still lost. The HTTP requests allow you to abstract bans into a database or other transactional store so you don't run into this problem.

**Comment by fazmond** [comment]
sticks there are already web configs I just don't have access to any webspace with the ability to chgmod to 777 as my provider is a windows box and they will not set the permissions for me
 
but surely you can check if the file is being read or written then just retry until the file becomes available again

**Comment by stickz** [comment]
Storing data locally is not a salable or proper solution for multiple game servers. The fundamental reason why text file handling is used - is for temporary storage of small amounts of data. Like to be able to recall a relatively small amount of data after it gets whipped from ram, from an event like a map change.

Something more abstract is required when elements such as multi-access and large amounts of data are introduced. It's a good practice to have a decent web hosting anyways for web related servers. In some cases a VPS, so you have full control over all web related aspects, by configuring everything yourself.
