### ISSUE TITLE
Map Voting Problem

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#590]
Since some time (probably since release of Shine Revision 258), the mapcycle that I am using is broken. It seems to ignore the "min" and "max" parameters and shows all maps (despite the ones with chance 0).
I have a picture attached which shows def_ maps in the mapcycle, even tho they should not be listed with that amount of players on the server. The used mapcycle can be downloaded here: https://dl.dropboxusercontent.com/u/19208003/mapcycle.json

 I am not sure, but maybe the issue is triggered with someone nominating for a map.

![mapcycle_bug](https://cloud.githubusercontent.com/assets/19150896/23590258/d8815c5a-01dc-11e7-8cbd-95853beec505.jpg)

**Comment by stickz** [comment]
@Person8880 
I can confirm that min perimeters aren't working on my server either.

**Comment by Person8880** [comment]
This should be fixed now.
