### ISSUE TITLE
AFK Plugin warns players to get kicked but KickOnConnect is active

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#591]
The AFK plugin is wrongly telling AFK players through chat message that they will be kicked in X seconds even tho the paramater KickOnConnect is active. That should not happen, as the time is of getting kicked with KickOnConnect can be dynamic.

Also the warn message is displayed even tho the server is not full and you setup to have the kick function active only when full.

**Comment by Person8880** [comment]
The warning message should make more sense now, and only be displayed if the player count is high enough to start kicking.
