### ISSUE TITLE
All talk turning off after a voterandom shuffle despite no commanders

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#594]
I don't really have any logs I can post of it as nothing gets generated - but it appears randomly, I'd say more than 50% of the time, All Talk will turn off in pregame immediately after a shuffle, despite no commanders being in the chair or when there is only one commander in.

Replicating it has been hit or miss, but I feel like it's still worth mentioning. I'm not sure whether it's related to the Pregame plugin or the voterandom plugin. It's worth noting that this happens long before the 60 second timer on pregame expires.

**Comment by Person8880** [comment]
The only thing that would turn the all talk off would be the game state changing, which would mean commanders are ready or it's forcing the game to start.

Can I see your `PreGame.json` config file?

**Comment by TA-Red** [comment]
{
    "AbortIfNoCom":true,
    "AllowAttackPreGame":true,
    "CountdownTime":10,
    "MinPlayers":0,
    "Mode":2,
    "PreGameTime":60,
    "ShowCountdown":true,
    "StartDelay":0,
    "__Version":"1.6"
  }

Although now that I'm looking at this I have no idea what that version qualifier is as I never put it in there. I'll remove it and see what happens. :|

**Comment by Person8880** [comment]
`__Version` is an internal field used to track the plugin version the config matches up to. It was added in a recent update, and won't be the cause of your issue.

**Comment by woozasmoddingteam** [comment]
I can confirm this new bug with b314.

AllTalk says it's disabled but not both teams have a commander and pregame is still active.

**Comment by Wooza42** [comment]
I can confirm this new bug with b314.

AllTalk says it's disabled but not both teams have a commander and pregame is still active.

It also bugs before even Shuffle.

**Comment by Person8880** [comment]
Are you certain it's disabled, or does it just say it's disabled and you can still hear everyone? There was a small issue with the text not being updated correctly.

**Comment by TA-Red** [comment]
I'm almost 100% positive it's actually disabled, as we've tried to communicate between teams and spectators and nobody can hear anything but the team they're on.

I'll further confirm it later today. Alternatively I'll ask others who are also experiencing it to see if they've confirmed it without a doubt.

**Comment by Person8880** [comment]
I see the problem. The last update to NS2 has changed the behaviour of warm up. It's now putting the game into the `PreGame` state when the number of players is larger than the warmup limit, rather than into `NotStarted` as it was before.

The plugin uses `PreGame` to indicate the game is going to start soon and all-talk turns off. So basically, a backwards-incompatible change was made to NS2 which has caused this.
