### ISSUE TITLE
Commanders being shuffled

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#598]
Commanders are sometimes being shuffled by the voterandom plugin despite it being to configured to ignore them.

**Comment by Person8880** [comment]
I'm having trouble reproducing this or seeing how the code can allow this to happen.

In the next update, there will be a new setting in the shuffle plugin config called `LogLevel`. Please set this to `"Debug"`, and then when you see it swap commanders, post back the part of the Shine log file around the time it occurred. That should help me see why they're swapping.

**Comment by SupaFred** [comment]
Thanks, I will.

/Fred

**Comment by SupaFred** [comment]
At 17:39 player 93723781 was shuffled while being commander.
https://www.dropbox.com/s/shmulr5gajgcsoe/log-Server.txt?dl=0

Fred

**Comment by Person8880** [comment]
I believe I've found the problem (and it was actually worse than just swapping commanders). Should be fixed in the next update.
