### ISSUE TITLE
Shine Pregame bugged

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#599]
It's a bit difficult to describe but somehow the shine pregame plugin no longer resets the game when leaving the vanilla "Warm-Up Mode". That means higher lifeform during pregame and gorges who can still build stuff. I am not sure but the "Warm-Up Mode" should automatically end when there is more than 6vs6 in teams, then usally the Shine Pregame Plugin forced a reset if I am correct.

My config of Pregame.json :
{
    "AbortIfNoCom":true,
    "AllowAttackPreGame":false,
    "CountdownTime":30,
    "MinPlayers":0,
    "Mode":3,
    "PreGameTime":9999,
    "ShowCountdown":true,
    "StartDelay":70,
    "__Version":"1.6"
  }

**Comment by Person8880** [comment]
The pregame plugin left vanilla code to handle warm up. They removed the reset of the game in the last update to NS2.

**Comment by Wooza42** [comment]
Oh okay, so this is intended? It's just weird with stuff like Hydras, that they keep attacking Players etc.

**Comment by Person8880** [comment]
I'm not sure if it's intended or what the thought process was, but it is in the patch notes:
> The game is no longer reset when switching between warmup and pregame state.
