### ISSUE TITLE
Dropbox links 404

### ISSUE THREAD

**Issue by Laaas** [Person8880/Shine#602]
The links to the example client.lua, server.lua, shared.lua
https://dl.dropboxusercontent.com/u/93261/sharedplugin/client.lua
https://dl.dropboxusercontent.com/u/93261/sharedplugin/shared.lua
https://dl.dropboxusercontent.com/u/93261/sharedplugin/server.lua

**Comment by Person8880** [comment]
Thank you Dropbox for pointlessly disabling public links, yet not really.

Hopefully I've caught them all. Let me know if you spot more of them.
