### ISSUE TITLE
'sh_rcon speed' bypasses the requirement for sv_cheats to be enabled.

### ISSUE THREAD

**Issue by AlexJFox** [Person8880/Shine#605]
Server ops have reported that they can alter the game speed without first enabling cheats by using sh_rcon. This seems like a bug to me, can you please confirm? I believe shine should respect the need for cheats/tests to be enabled with sh_rcon for all commands.

**Comment by Person8880** [comment]
The `sh_rcon` command is literally just using `Shared.ConsoleCommand()`. The problem's in the engine code responsible for that or the speed command itself, which are out of my control.
