### ISSUE TITLE
Players avoid bans via Steam's Family Sharing

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#606]
Lately a increasing number of players are using Steam's Family Sharing to avoid bans.

It would be great if the following two features could be added to Shine:
1. Log the parent's steam id when a client using family sharing connects to the server.
2. Add an option to also ban the parent when banning a client using family sharing.

These features would make it a lot easier for server admins to detect and prevent abuse of Steam's family sharing feature.

**Comment by Person8880** [comment]
Should be solved with the new `BanSharerOnSharedBan` option.
