### ISSUE TITLE
Latest Update Restricting All basic user access intentional?

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#609]
Basically it's more of a question and reporting of a possible bug.

Was it intentional to have the new "DefaultGroup" automatically be necessary for any regular user to have access to commands?

As an example, without the DefaultGroup added into my UserConfig.json no users can access any of the normal default Shine commands. Was it intentional to lock them out? Will DefaultGroup be a necessary addition to the Shine UserConfig.json from here on out? Many users were reporting being locked out to those most basic of commands (stuck, voterandom, etc) on multiple servers, so I know it can't just be my userconfig.

Or is it all just a bug and was DefaultGroup only intended to be used if we wanted to?

**Comment by Person8880** [comment]
No, it's not intentional. I've just released a fix for it so you shouldn't need a default group now, sorry about that.
