### ISSUE TITLE
VoteRandom - Option to disable shuffle once a game started

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#610]
I personally do not really like that people can still vote for shuffle once a round started. If the vote is successful, the round will be reset immediatly and players are often confused for a second. Therefor I would like to have an option which removes VoteRandom once a round started.

Also to improve a successful shuffle vote during a round, I recommend to display  a notification somewhere on the middle of the screen, that the teams will be shuffled now and the round reset, before actually reseting and shuffling.

**Comment by GhoulofGSG9** [comment]
Just set `BlockAfterTime` to `0.01` in the `VoteRandom.json` to block shuffle votes after the round has started.
