### ISSUE TITLE
Add webhook to allow modders on Discord to see commit messages

### ISSUE THREAD

**Issue by AlexJFox** [Person8880/Shine#612]
Not an issue with Shine, but I sent you a webhook in a message on the forums, if you would consider adding this to your repository settings, it would allow modders on the Discord server to see commits as you make them, keeping them up-to-date without having to monitor github. Entirely up to you but would be very useful. Thanks for considering!

**Comment by Wooza42** [comment]
Bumping this cause it is a nice idea

**Comment by Person8880** [comment]
I don't see the benefit vs. using GitHub's notifications. If you want to be notified of commits/changes, then you can watch the repository.
