### ISSUE TITLE
Admins/Mods/ranked users now vulnerable to votekick

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#616]
I'm not sure if this was another intentional/unintentional change as I can't see it in the change log.

It used to be any user that had a rank would be immune (1 and higher) was immune from being votekicked. I'm not sure if it was because of the latest update to NS2 or an update with Shine but that doesn't seem to be the case anymore.

If intentional, is there any way to re-enable this immunity?

Thanks!

**Comment by Person8880** [comment]
This was broken by a change in the last NS2 update, should be fixed now.
