### ISSUE TITLE
Starting kickvote against player with higher immunity

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#619]
I have seen that a player with immunity 5 started a kickvote against a player with a immunity of 6. As far as I understood the immunity system, that shouldn't be possible and Shine should print a message that the targeted player has a higher immunity. Pretty sure it's a bug as it used to work in the past.

My userconfig can be found here: https://pastebin.com/a37msiEM
The user that targeted the user with higher immunity was in the group "DefaultGroup" and the targeted person was in the group "Sandy".

To mention: I have the parameter in userconfig set to true: "EqualsCanTarget" As I want that players in the same group / same immunity can kick each other.

**Comment by Person8880** [comment]
The immunity check works as far as I can test.

However, your config has a few syntax errors, so it's probably not loading at all. I've fixed them here: https://pastebin.com/7A5xCHXL

Give that a try and hopefully it resolves the problem.

**Comment by Wooza42** [comment]
Thank you a lot! Do you remember btw where I did the Syntax error? And is it possible that shine displays the error in the console (Usually it says on which line I had made a mistake)?

**Comment by Person8880** [comment]
It should definitely log any syntax errors, but it will only log the first one it encounters.

The errors were:

* Missing comma on line 164.
* Missing comma on line 1289.
* Missing key for the group `Idiots` on line 1683 (you had just `{ "1": ["wrench2", "sysop" ], "2": [ ]}`, it needed to be `"Badges": { "1": ["wrench2", "sysop" ], "2": [ ]}`).
