### ISSUE TITLE
Shine Chatbox

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#621]
With latest build (b315) I have observed that underneath the Shine Chatbox, sometimes the vanilla Chatbox can be found. It's not happening all the time and I don't know the reproduction step yet, but I think it has something with the buggy Pregame / warmup mode.

Screenshot of bug attached
![20170606232114_1](https://user-images.githubusercontent.com/19150896/26897581-55a0d892-4bc9-11e7-8884-9ce769d14b5b.jpg)

**Comment by Person8880** [comment]
Fixed in the next update, thanks for reporting.
