### ISSUE TITLE
Shine Pregame Bug

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#622]
Okay this time it's getting very difficult to explain:

There is a strange bug that (most likely) occurs when you go spectator and watch someone in pregame. To mention: I think the bug is related to the issue here: https://github.com/Person8880/Shine/issues/599 where the players who joined during Warmup are not losing their lifeform and therefor can still shoot, place stuff such as clogs and hydras.

So if you go Spectator and you watch one of the guys in warmup (First Person view), then when the warmup limit is reached, ends and Pregame kicks in, the UI of the spectator gets totally messed up. Here are some screenshots:
![20170605233648_1](https://user-images.githubusercontent.com/19150896/26898247-7c4936f4-4bcb-11e7-9f1e-faf9f31dac95.jpg)
You can see the HUD of the marine in the screen
![20170605233719_1](https://user-images.githubusercontent.com/19150896/26898256-7e26dcec-4bcb-11e7-9d87-030d5626d0cf.jpg)

And here is the script error (Sorry I did not make a copy of the log.txt file):
![20170605233706_1](https://user-images.githubusercontent.com/19150896/26898278-8cc02fe2-4bcb-11e7-826c-3645c2f5d06c.jpg)

It makes no sense for me, that there is no reset when Warmup ends and Pregame starts. Players in Warmup should lose their lifeforms and be able to produce annoying sound with shooting constantly cause all players nearby hear it

**Comment by Person8880** [comment]
The only thing Shine is doing is setting the game state. This is almost certainly a bug in NS2.

The lack of reset when enough players join to end warm-up was a vanilla change, presumably to prevent constant resets if players join/leave around the warm-up threshold. I could change this behaviour, but I imagine they changed it for a good reason.
