### ISSUE TITLE
Allow servers to adjust when the automatic vote for comm bots occurs

### ISSUE THREAD

**Issue by keatsandyeats** [Person8880/Shine#625]
I think it would be useful for servers to control at what time the automatic commander bot vote occurs.

(The recent vanilla NS2 update 315 introduced two ServerConfig values to manage voting for commander bots. But you can't adjust the time with those.)

`NS2Gamerules.kStartGameVoteDelay` may be relevant for this.

**Comment by Person8880** [comment]
This is implemented in the `BaseCommands.json` config option `CommanderBotVoteDelayInSeconds` in the next update.
