### ISSUE TITLE
Vote Random - 60 second hard coded delay needs configurable option

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#627]
The problem is that I have 22 people on my servers.
within 20 seconds of a map change, shuffle passes, and shortly thereafter the game starts - and because afk's are shuffled onto teams, we have 6 afk's at the start of the game.

Could we please lower that 60 second threshold to 30 seconds or make it a configurable option please?

**Comment by Person8880** [comment]
The next update will use the `VoteSettings.AFKTimeInSeconds` option to determine how long a player has to be AFK to move them into the ready room and ignore them in shuffles.
