### ISSUE TITLE
FEATURE REQUEST set a players Display name while on a server

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#628]
OK firstly this is not so the admins can abuse the player as they could already do this with the !rename command from the NameFilters Plugin.

what I want is to be able to set a players name in the user config so it displays on the score board and ingame while hes on our server , I have a few reasons for this feature, but lets not get into that, lets focus on this feature

**Comment by fazmond** [comment]
would be nice to just have 
player name "****",
in the config

**Comment by Person8880** [comment]
The next update will have a `ForcedNames` table in the name filter plugin's config. Add NS2 IDs and the name you want to force there, e.g.
```json
"ForcedNames": {
    "123": "NSPlayer123"
}
```

**Comment by fazmond** [comment]
its great and I'm using this thanx !
