### ISSUE TITLE
WebURL Bans problem

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#629]
I'm not sure what wrong with this but when I set it up it was all working fine

the ban list some times decided to clear its self
and now I'm having an issue where the bad read from the web url ok 
but when you try and post a ban it comes back with the error
received INVALID JSON. Error: no valid JSON value at line 1, column 1

I though it was the URL bans file its self at first but its not 
permissions are 777 on the file and folder and the CORRECT auth key is being used

**Comment by Person8880** [comment]
This would mean that your web server is not returning valid JSON.

Are you certain the URL and parameters are correct? Can you apply the same parameters and receive a correct response through other means (e.g. a web browser)?

**Comment by fazmond** [comment]
if I upload a file myself the server reads it ok 
its just the adding a ban
url params are correct

**Comment by fazmond** [comment]
when i first set this up it was working just fine across my 4 servers but every now and again it would clear the ban list

**Comment by Person8880** [comment]
If you're getting an error about invalid JSON when submitting a ban, then that just means your server is not responding to the request with JSON. It expects a response of the form:
```json
{
    "success": true
}
```
The bans plugin will essentially ignore any non-JSON response and do nothing to remove the ban that was added.

If you're getting empty ban lists then that would imply a failure elsewhere to retrieve the bans on startup. There should be error messages when this occurs, starting with `[Error] Loading bans from the web...`.

**Comment by fazmond** [comment]
ok heres an update 
the server can read the band from the web ok 
it just cannont write to the web
and yes 777 is on both files and folder
is there a problem with the ban handler?

**Comment by fazmond** [comment]
would be nice for an example on bans.json

**Comment by Person8880** [comment]
What are you using to submit bans to? Is it [the example script](https://github.com/Person8880/Shine/wiki/Bans#web-api-example)?

**Comment by fazmond** [comment]
yer what you have in handle_ban.php

**Comment by fazmond** [comment]
its pretty frustrating cause when I first set it up it was working for like a month

**Comment by Person8880** [comment]
Is the `auth` value correct in the config and script? Can you check the logs of your server to see if there's any errors around requests to the script?

**Comment by fazmond** [comment]
the auth is set in both where am I looking for the logs?

**Comment by fazmond** [comment]
[02:12:41]Shine loaded bans from web successfully.
[02:12:41][Bans] Received invalid JSON for unban of 431828193. Error: no valid JSON value at line 1, column 1 from the shine logs

**Comment by Person8880** [comment]
Sorry, I meant the web server. Either it's not receiving all the parameters it expects or something's blowing up part way through, which I would hope is logged.

**Comment by fazmond** [comment]
its just some Linux webspace I don't think I have any logs for it

**Comment by Person8880** [comment]
Nothing for the PHP script? Is `BansSubmitURL` pointing at it or `Bans.json`?

That log implies it might be pointing at the wrong place given it's hitting the JSON file with a POST.

**Comment by fazmond** [comment]
any chance of a discord or steam chat ?

**Comment by fazmond** [comment]
http://steamcommunity.com/id/MrFaz/

**Comment by fazmond** [comment]
ok seems to be working now was to do with the pointing, I'm just wondering what happens on a shared ban list across 3 server when a ban is removed , does it sync the ban list again upon server map change or restart so the other server know to remove the ban ?

**Comment by fazmond** [comment]
what I mean is does the ban list overwrite from the web to the server every restart or map change?

**Comment by Person8880** [comment]
Yes. As long as it can successfully retrieve the bans file from your web server, the local data is overridden with any changes made on map change/restart.

**Comment by fazmond** [comment]
great chears m8 ya can close this for now thanx 📦
