### ISSUE TITLE
Feature Request: Carry over gags after map change

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#631]
It would be great if there was a way to add permanent gags as opposed to resetting on the map change.

There are individuals that I wouldn't mind playing on the server, but when they contribute to voice/text chat, they're nothing but toxic.

I figure it would be much similar to commbans, and even if it wasn't, perhaps a json we could add IDs to that would automatically gag those IDs for the maximum duration upon entering the game/switching map (if it detects them).

Thanks!

**Comment by Person8880** [comment]
The next update will have:

* A new table (`GaggedPlayers`) in the `BaseCommands.json` config for adding players to be gagged permanently, e.g.
```json
"GaggedPlayers": {
    "123456": true
}
```
* Two commands to add/remove permanently gagged Steam IDs in-game
  * `sh_gagid <steamid>` - adds the given ID to the config
  * `sh_ungagid` - removes the given ID from the config
