### ISSUE TITLE
Shuffle is not removing vanilla bots. Causing issues.

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#637]
Vanilla bots are enabled. Shines botManager is disabled. When vanilla bots are enabled, and someone joins a team after map change, both teams populate with bots. If a shine shuffle goes through, it will shuffle people onto the teams and not remove the bots. What I'd like shine shuffle to do is run the vanilla "randomize ready room" command first, as this removes the bots, and then have it shuffle.

Thank you for everything you do @Person8880 ! Much appreciated!!!!

**Comment by Person8880** [comment]
The `ApplyToBots` setting controls this. Make sure it's set to `false` and bots should be kicked when a shuffle vote passes.

**Comment by Rusty01** [comment]
ApplyToBots is set to false, bots are still not being kicked.

**Comment by Person8880** [comment]
The next update should prevent bots from appearing again until the end of the round after a shuffle vote.
