### ISSUE TITLE
License for /lua/shine/lib/locale.lua

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#639]
The Locale lib in Shine would be very helpful to others to help translate their mods. What license, if any, does it fall under? If it is not a permissive license, would it be possible to release it as a standalone lib using a permissive license?

Thank you!

**Comment by Person8880** [comment]
The code is not currently under any open source license, so you wouldn't be able to use it in another project directly.

That being said, what's the issue with using it alongside Shine from the workshop? You can register your own sources and use it without needing a plugin if you want.

**Comment by TheRealNin** [comment]
Thanks :) I'll see about using it alongside Shine.
