### ISSUE TITLE
Shine extension "Tournament Mode" crashes servers

### ISSUE THREAD

**Issue by turtsmcgurts** [Person8880/Shine#642]
The plugin rewrites the serverconfig on plugin initiliase incorrectly. to keep things short and sweet:

what the config should and normally looks like:
```
    "auto_team_balance":{
      "enabled_after_seconds":0,
      "enabled":false,
      "enabled_on_unbalance_amount":2
    },
```

what Tournament Mod changes it to ([line 79](https://github.com/Person8880/Shine/blob/master/lua/shine/extensions/tournamentmode/server.lua))
`
    "auto_team_balance":false,`

i understand that this is a rare crash because the population of the game is low, and those who run this specific extension is minuscule so it's understandable if a fix isn't worth the time right now, but perhaps this extension could be globally disabled until then to prevent people from accidentally bricking their configs.

in fact, there's only been two (according to my google searches) reports of this crash happening and they're both by friends of mine hosting a "Captains" server one year apart. I honestly wouldn't be surprised if nobody else has really used the plugin, as it's a very niche thing in a equally niche game. [report one](https://forums.unknownworlds.com/discussion/136324/config-file-corrupts-itself), [report two](https://steamcommunity.com/app/4920/discussions/0/611703709825588168/).

thanks and i appreciate your work with shine! 👍

**Comment by Person8880** [comment]
Fixed with 0b2f12112c4497708091b5149ffa3425dadb5e07.
