### ISSUE TITLE
Option to move sh_afk_partial clients to spectate

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#644]
Could a feature be added to the afk_kick plugin to move clients with `sh_afk_partial` to spectate regardless of what `MoveToSpectateOnWarn` is set to? 

I want to make sure admins on my server don't block people from connecting when going afk. But at the same time, regular players who go afk don't fill up the limited number of spectate slots. 

Spectator slots have a negative impact on server performance, when too many are used.

**Comment by Person8880** [comment]
7ca97bc6061bf95339bc29c9787d220ac1d6c9d9 changes the warn action configuration to allow for separate actions for immune vs. not immune clients.

The old `MoveToSpectateOnWarn`, `MoveToReadyRoomOnWarn` and `Notify` options have all moved into `WarnActions`.

As an example:
```json
"WarnActions":{
    "NoImmunity":[ "MoveToReadyRoom", "Notify" ],
    "PartialImmunity":[ "MoveToSpectate", "Notify" ]
},
```
This would move non-immune clients to the ready room when warned, as well as notifying them with a sound. Partially immune clients would move to spectate instead, and also be notified with a sound.
