### ISSUE TITLE
Improve shine shuffling

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#645]
Could a feature be added to shine shuffle to immediately shuffle when the round starts instead of instantly, when the round is not started. Having to constantly reshuffle before round-start is annoying. It also gives players a greater opportunity to stack teams because they have nothing to lose if the round isn't started.

**Comment by Person8880** [comment]
The `AlwaysEnabled` option forces a shuffle at round start, is that not what you are after?

**Comment by stickz** [comment]
No, I only want it enabled when people vote for it. I want the shuffle to trigger when `AlwaysEnabled` does instead of at round start. Instantly shuffling gives people time to stack before round start.

**Comment by stickz** [comment]
Also, could you add a setting to force a shuffle if the skill average is greater than a certain percent and the specified min players is reached. I don't want to always force shuffle, just sometimes when required.

**Comment by stickz** [comment]
Furthermore, i'd like shuffle to have the capability to reset the round and shuffle in the first x number of minutes when a vote passes; to give players an opportunity to correct imbalanced teams and shuffle.

**Comment by Person8880** [comment]
I have significantly refactored the configuration for the plugin now, as in its old state it was very unclear how to set it up.

The configuration now allows configuring when the shuffle should be performed, and how it should be enforced separately for votes passing in the pre-game time, and votes passing mid-round.

This config below should give you what you want:
```js
// Block any votes after 5 minutes into a round.
"BlockAfterTime": 5,
"VotePassActions":{
  // For votes passing mid-round, instantly shuffle (which resets the game) and enforce for the round's duration.
  "InGame":{
    "DurationInMinutes":0,
    "EnforcementDurationType":"PERIOD", // PERIOD means for the entire duration of the stage the shuffle was triggered in
    "EnforcementPolicy":["ASSIGN_PLAYERS","BLOCK_TEAMS"], // These are the actions to apply while teams are enforced
    "ShufflePolicy":"INSTANT" // Apply shuffle immediately when the vote passes
  },
  // For votes passing in the pre-game, queue a shuffle for the next round, and enforce it for that entire round.
  "PreGame":{
    "DurationInMinutes":0,
    "EnforcementDurationType":"PERIOD",
    "EnforcementPolicy":["ASSIGN_PLAYERS","BLOCK_TEAMS"],
    "ShufflePolicy":"END_OF_PERIOD" // Apply shuffle at the end of the pre-game (start of next round)
  }
}
```

The full set of options will be documented on the wiki when I release the next update.

The only thing missing is the auto-shuffle when skills differ too much. I'm not entirely keen on adding it, as it may end up continuously triggering if players fight it, or if the teams are not able to be balanced closely enough. I don't think it would be a pleasant experience for players to keep being swapped around against their will, whereas at least a vote is something they can control.
