### ISSUE TITLE
Individual User Permissions

### ISSUE THREAD

**Issue by Soggeh** [Person8880/Shine#648]
Hi, may I ask if it is possible to add command access to users individually rather than having them to be in user groups? 

If not, are there any workarounds i can carry out? Thanks for the awesome mod :D

**Comment by GhoulofGSG9** [comment]
The workaround is to just define a group for the given user with the given access rights inheriting the group the user was originally intended to be in.

**Comment by Person8880** [comment]
Groups are the most flexible way to define permissions. There's not much difference between individual groups for specific users and having the permissions on the user themselves, except the groups can be re-used later if desired.
