### ISSUE TITLE
VoteRandom is moving commanders

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#650]
VoteRandom is moving commanders even though it's set to ignore them. See log at 17:58 where I (120890448) was moved while being in the command chair.
https://www.dropbox.com/s/shmulr5gajgcsoe/log-Server.txt?dl=0

**Comment by Person8880** [comment]
Should be fixed now. I forgot about the case where commanders aren't allowed to be swapped when swapping the teams around due to team preferences.
