### ISSUE TITLE
Datatable variable don't accept type "table"?

### ISSUE THREAD

**Issue by tsKenneth** [Person8880/Shine#657]
Hi, i tried to use "table" but it doesn't work. Is it implemented? Otherwise would there be any workaround for it (I thought of using loops and sending network message instead)? Thanks.

**Comment by Person8880** [comment]
There is no `"table"` type available for network messages.

Are you trying to send a list of data, or just a sub-table? If the former, the only way to do it is to send multiple messages. If the latter, then your best bet is to flatten it to the top level.

**Comment by tsKenneth** [comment]
It's the former. I've accomplished it by sending multiple messages. Thanks.
