### ISSUE TITLE
AFK Plugin: KickOnConnect

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#659]
Hey Person8080

I wonder how the KickOnConnect function works in detail. How does Shine know that someone tries to "queue"? Also I don't believe that currently it's doing the job properly and AFK's rather stay for too long AFK (longer than the kicktime) till they get kicked ( I know the setting is beta / unfinished)

**Comment by Person8880** [comment]
It doesn't really know when a player queues, it only knows when a connection attempt is made.

I'm not 100% certain on whether the engine tells Lua about players connecting when the server is full or not. If it doesn't, then it would be able to kick players when there's at least one player/spectator slot still open.
