### ISSUE TITLE
[Vote-Random] Add option to disable the shuffle vote after x minutes into the round.

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#661]
It may be useful for some server admins to be able to set a limit how long into a round players are able to vote to shuffle teams (specially when the instant shuffle policy is used).

There have been some complaints about players voting to shuffle instead of surrendering, causing a reset 30+ minutes into the round.

**Comment by Person8880** [comment]
This already exists. The option is `BlockAfterTime`, which is a time in minutes after which the vote is blocked.

**Comment by GhoulofGSG9** [comment]
Oh I guess I overlooked that option while checking the config yesterday. Thanks for your reply. I will close this ticket now as it has been resolved.
