### ISSUE TITLE
FEATURE REQUEST vote ALLTALK

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#662]
FEATURE REQUEST vote ALLTALK

maybe this could be added so that players can vote it on or off with some configuration file

when were filling/seeding a server I turn all talk on for the guys filling but then I'm not always there when the server gets filled 
so would be nice if the players could vote this on or off from the vote menu

**Comment by Person8880** [comment]
This will be in the next update as a new plugin named `votealltalk`, which is documented on the wiki here:
https://github.com/Person8880/Shine/wiki/Vote-All-Talk

**Comment by fazmond** [comment]
great thanx was fast too ! or had you been considering this before I suggested it :)
