### ISSUE TITLE
FEATURE REQUEST Adverts - template intervals, interval conditions, delay, and team specific, Multi line message.

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#664]
ok so with the adverts it would be nice if you could set the intervals within specific templates
**REASON** perhaps you want template "hints" to spam every 1 minute but want to give out "info" every 5 mins

**interval condtions (start,end,time/delay)**
would also be nice if you could set the advert to show at the beginning of the timer or at the end or at a specific sedond within the timer
**REASON** (start,end) if you set a 5min timer the message will not appear late and perhaps you want it showing straight away 
(time/delay) perhaps you want the messages to start 30 seconds after the map changes so it gives players time to join the server so they don't miss any messages .

**TEAM SPECIFIC**
would also be nice to be able to put in the template who you want to show the adverts to 
ie TEAM1 TEAM2 SPEC READYROOM
**REASON** you might only want some adverts shown in the ready room and spectate but not into the players playing the map , or just alien or marine specific "hint adverts". or any combination, if no team is set then the advert should show in all .

**MULTI LINE MESSAGE**
it would also be nice to have the ability to have a multi line message in the one advert with the ability to colour each line

"TriggeredAdverts": [
          {
            "Colour": [ 255, 255, 0 ],
            "Message": "VEIL_CYCLEMAP - HINTS",
            "Colour": [ 255, 255, 355],
	    "Message": "There is no middle of the map",
            "Message": "Try to push tunnels/pg's as far forward as possible.",
            "Message": "Try to get behind the enemy's front lines.",
            "Message": "Better to Group up than to battle solo.",
            "Template": "Cyclemaps",
            "Trigger": "COUNTDOWN"
        },
**REASON** this would be a great way of advertising a list of hints as the game started , or even you might want to have the first message coloured and the other lines a different colour to highlight your adverts proplery.

just some thoughts to make adverts better.

**Comment by fazmond** [comment]
who to show adverts to + map specific advert conditions could really help with custom maps

for example ns2_unearthed map
advert 1 to aliens "Marines always start in entrance"
advert 2 to both teams "Center of the map is very important"
and so on .....

**Comment by fazmond** [comment]
or even show adverts to specific hives kill levels if you wanna take it that step even further

**Comment by Person8880** [comment]
The next update expands adverts to be able to:

* Specify as many cycles of adverts as you want.
* Specify start/stop triggers for advert cycles (`StartedBy`/`StoppedBy`).
* Make cycles that only display their adverts once and then stop (`"Loop": false`).
* Specify a delay per message/template (`DelayInSeconds`).
* Specify a team filter for messages (using the `Team` field which may be one of `MARINE`, `ALIEN`, `READY_ROOM` and `SPECTATOR`).

For example:

```js
{
    // This is now a list of advert cycles, rather than one cycle.
    "Adverts": [
        {
            // Specifies a default template for all messages in the cycle.
            "DefaultTemplate": "ChatNotification",
            // Specifies the default interval between messages.
            "IntervalInSeconds": 60,
            // Specifies the initial delay before the first message when this cycle starts.
            "InitialDelayInSeconds": 30,
            "Messages": [
                {
                    "Message": "Welcome to Natural Selection 2"
                },
                {
                    "Message": "This server is running the Shine Administration mod."
                }
            ],
            "RandomiseOrder": false
        },
        // This is a second cycle, that will start at round start and stop at round end.
        {
            "DefaultTemplate": "ChatNotification",
            // This initial delay means that when the round starts, the first message will be
            // displayed immediately with no delay.
            "InitialDelayInSeconds": 0,
            "IntervalInSeconds": 60,
            // It is possible to disable looping by setting this to false.
            // A non-looping cycle stops itself when it has displayed all of its adverts.
            "Loop": true,
            "Messages": [
                {
                    "Message": "Marines always start in entrance",
                    "Team": "ALIEN"
                },
                {
                    "Message": "Center of the map is very important",
                    "Team": [ "MARINE", "ALIEN" ],
                    // You can specify a delay per message. This means that 30 seconds after
                    // the previous message, this one will display.
                    "DelayInSeconds": 30
                }
            ],
            "RandomiseOrder": false,
            // Cycles can be triggered using the same triggers as triggered adverts.
            "StartedBy": [ "START_OF_ROUND" ],
            "StoppedBy": [ "END_OF_ROUND" ]
        }
    ],
    "LogLevel": "INFO",
    // Templates are unchanged, but may also specify delays.
    "Templates": {
        "ChatNotification": {
            "Colour": [ 255, 255, 255 ],
            "Prefix": "[Info]",
            "PrefixColour": [ 0, 200, 255 ],
            "Team": [ "READY_ROOM", "SPECTATOR" ],
            "Type": "chat"
        },
        "ns2_veil": {
            "Maps": { "ns2_veil": true }
        }
    },
    // Slightly different format for triggered adverts to make it easier to follow.
    "TriggeredAdverts": {
        // You can specify as many triggered adverts for a given trigger as you want.
        // All of these will show at the start of the countdown, in the order defined here.
        // This gives you multi-line adverts. For more advanced use/categorisation, make a non-looping
        // cycle in the "Adverts" list above instead.
        "COUNTDOWN": [
            {
                "Message": "VEIL_CYCLEMAP - HINTS",
                "Colour": [ 255, 255, 0 ],
                "Template": "ns2_veil"
            },
            {
                "Message": "There is no middle of the map",
                "Template": "ns2_veil"
            },
            {
                "Message": "Try to push tunnels/pg's as far forward as possible.",
                "Template": "ns2_veil"
            },
            {
                "Message": "Try to get behind the enemy's front lines.",
                "Template": "ns2_veil"
            },
            {
                "Message": "Better to Group up than to battle solo.",
                "Template": "ns2_veil"
            }
        ]
    },
    "__Version": "2.0"
}
```

**Comment by fazmond** [comment]
This is great m8 really honestly I can say some of the best support of a mod that's really quite important if I think of anything else will or find issue I will post here, gonna have a play with it now

**Comment by fazmond** [comment]
is there a game state for game in action ?

**Comment by fazmond** [comment]
one more thing is there a way to set a timeout for the message so it stays on the users chat for more than 5 seconds before it fades away? if no other message had been posted ?

**Comment by Person8880** [comment]
The chat message display is controlled by the game, which provides a client-side option for how long messages stay on screen (`chattime` in the console). It doesn't have a way to set timeouts for messages individually.
