### ISSUE TITLE
FEATURE REQUEST - Welcome Messages Colored,Time Played,some stats

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#668]
would be nice if you could colour the join/leave messages

id like to highlight players/admins when they join and leave the server 
be it with a coloured prefix like your adverts have or just the ability some how to colour each word or by letter

and maybe even have some ability to add some information that the server might track , like time on server or some other stats.
_example_
[ADMIN] FAZ has left the server. (time played 1hour30mins) (1kill/68deaths)

just an other improvement on an already great admin mod

**Comment by Person8880** [comment]
You can now alter the colour of messages and set a (coloured) prefix on them in the same way as for adverts. See here:
https://github.com/Person8880/Shine/wiki/Welcome-messages#message-format

**Comment by fazmond** [comment]
yer thanx works a treat and thanx for the recent updates
