### ISSUE TITLE
Welcome Messages "Said":true,

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#670]
so I was editing the txt file for the Welcome messages 
and noticed this 
Welcome Messages "Said":true,
there is nothing on the wiki about it but while I was edting the file the server must of changed maps and it then over wrote when I put in the config.
should I be disabling the plugin while I edit it ?

**Comment by Person8880** [comment]
This is to allow it to track which messages it has already said between map changes. It's not the best solution, I could move that information into a separate file to avoid it rewriting the config.

**Comment by fazmond** [comment]
yer its just I lost a lot of changes while server was live

**Comment by Person8880** [comment]
Best practise is to always edit a copy of the config and copy it back into the config directory when you're finished.

The next update will remove the `Said` key from any entries that have it and use a separate file for tracking messages instead.
