### ISSUE TITLE
AFK Plugin false positive results

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#671]
Hey Person8880

I open another thread as I am still seeing the AFK plugin doing some false decision. I stumbled open this thread where this guy mentioning the same: http://steamcommunity.com/app/4920/discussions/0/1697167355214737569/

It's a rare problem that occur sometimes with players. In my case, they always get sent into the readyroom after 2 min playtime. I saw with my own eyes when my girlfriend played NS2 and sent back to RR all the time saying she will be kicked after 3 more mins.

Is there any possibility to help tracking down this problem?

**Comment by Person8880** [comment]
Set `LogLevel` to `DEBUG` and see what it logs when it moves/kicks someone.

**Comment by Person8880** [comment]
One thing you can also try now is to disable Steam overlay checks by setting `CheckSteamOverlay = false` and see if it removes the problem.

**Comment by Person8880** [comment]
I've completely removed the Steam overlay check as I'm pretty sure that the engine function is reporting that it's open sometimes when it's not.

As far as I know there are no other potential false positives left, so hopefully it will be fixed.
