### ISSUE TITLE
FEATURE REQUEST: Force map vote menu to show when a map vote is in progress

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#672]
It would be nice if one could force the map vote menu to be shown whenever a map vote starts and a game isn't in progress. Maybe there could be a corresponding client-side option to never have it shown to you.

**Comment by fazmond** [comment]
+1

**Comment by Person8880** [comment]
Will be in the next update as the `ForceMenuOpenOnMapVote` option.

Clients will also be able to override it in the client config menu to either never show, or always show regardless of server settings. The default is to respect the server settings.

**Comment by TheRealNin** [comment]
Thanks so much!
