### ISSUE TITLE
RTV: Disable after x minutes in a round

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#678]
I have a feature request for the votemap plugin:

Currently it can happen that a team, out of frustration is starting a RTV vote after like 30min ingame. I tried already to increase the value for a successful RTV but specs sometimes trolling as well and vote for RTV too. Hence the idea to disable RTV after x minutes in a map, once the round started.

**Comment by Person8880** [comment]
Will be in the next update as the `BlockAfterRoundTimeInMinutes` option. Set to a value greater than 0 to enable it.
