### ISSUE TITLE
"This vote has been disabled" when target user with higher immunity

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#679]
I do think it's not perfect wording when you try to target a player with a higher immunity than yourself. Instead of saying the vote is disabled, it should spit out something like that the user has higher immunity and therefor can't be targeted by the vote.

(I am not 100% sure if it's called "the vote has been disabled" but I do believe so. It might be slightly different as I havn't tested it for a long time).

**Comment by Person8880** [comment]
This should have been [fixed a while ago](https://github.com/Person8880/Shine/wiki/Changelog#revision-277---030218). Have you checked more recently than 3rd March this year?

**Comment by Wooza42** [comment]
Thank you Person8880 for the response. I don't think so, my bad! I will test it the next days. Thank you in advance
