### ISSUE TITLE
Mapcycle optimization: Not make it possible to vote for similar named maps after each other

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#680]
I would like some sort of setting in the mapcycle that allows me to prevent another (similar) map to be played afterwards. Our main problem is that it can happen that after ns2_veil, we play ns2_veil_five.
The new setting should not allow ns2_veil_five in the mapcycle after ns2_veil was played, even if it was nominated. Maybe take into account the values of "ExcludeLastMaps".

**Comment by Person8880** [comment]
Will be in the next update as the `ExcludeLastMaps.UseStrictMatching` option. The default is `true` which is the current behaviour.

Set it to `false` to allow it to consider maps that have the same base name as identical which should provide the behaviour you're asking for.

**Comment by Person8880** [comment]
In addition to the last map exclusions, there'll be another option (`ConsiderSimilarMapsAsExtension`) which controls whether to treat similarly named maps to the current map as an extension. If enabled, it will prevent them from showing up in the vote if extending the map is blocked.

**Comment by Laaas** [comment]
I am just wondering, how would this would work waterdome/biodome?
