### ISSUE TITLE
PreGame "All Talk Disabled" during countdown is not being disabled

### ISSUE THREAD

**Issue by Turbine1991** [Person8880/Shine#683]
What is happening is when the round is about to begin and the "All Talk Disabled" message appears, members of each team broadcast their strategy - unknowingly during the PreGame countdown duration. The alltalk disabling facility appears to be overridden as the round has technically not begun.

Below contains the overridden logic ['basecommands/server.lua'](https://github.com/Person8880/Shine/blob/master/lua/shine/extensions/basecommands/server.lua):
```
local function IsPregameAllTalk( self, Gamerules )
	return self.Config.AllTalkPreGame and **Gamerules:GetGameState() < kGameState.PreGame**
end
...
function Plugin:CanPlayerHearPlayer( Gamerules, Listener, Speaker, ChannelType )
...
	if self.Config.AllTalk or **IsPregameAllTalk**( self, Gamerules ) or IsSpectatorAllTalk( self, Listener ) then
		return true
	end
```

Obviously PreGame is technically a standalone addon to BaseCommands, therefore an additional PreGame consideration for the conditional 'PreGame.GameStarting' needs to be implemented.

**Comment by Person8880** [comment]
Are you certain that global all talk is not enabled? Both the text and the logic here are driven by the Gamerule's state. The text can only go red when the state is greater than `WarmUp`, which at least as far as vanilla game states are concerned, is `PreGame` onwards.

I suppose the text is a little misleading in the case where global all talk is enabled, though I'm not sure if having it displayed all the time is a good idea.

**Comment by keatsandyeats** [comment]
This sounds like what used to happen if you had vanilla's `pregamealltalk` enabled in ServerConfig. I haven't had a server in a year or so, but I would recommend disabling that in vanilla and just using Shine's options.

**Comment by Turbine1991** [comment]
@Person8880 I've confirmed global alltalk is definitely disabled, and all is disabled as soon as the countdown finishes and game begins.

@keatsandyeats Thank you Keats, that solved it. Vanilla's pregame alltalk was permitting voice during the countdown.
