### ISSUE TITLE
Shuffle request: Enable shuffle button only after certain criteria

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#685]
Hey Person8880

First, great job on the latest big shine update. Me and other server ops love it!

I have following request about the shine plugin shuffle:

I see that people often shuffle when the avg. team skill difference is not even that high or they just reshuffle after the previous shuffle already gave good results and even with people switching it's acceptable.

Therefor I would like to have an option that allows people to shuffle only when the actual avg. skill difference is way off. Optimally the server-op should decide by themselve when the actual team skill difference is "no longer balanced" and therefor define the skill difference to make the shuffle button show up.

To minimize confusion for players, maybe not make the button go away once teams are fine but print a message when the player clicks on or grey it out.

**Comment by Person8880** [comment]
Will be in the next update as the following options:

```js
"VoteConstraints": {
    // Minimum fraction of players on the server needed on playing teams to apply constraints.
    "MinPlayerFractionToConstrain": 0.9,
    // If difference in average skill is larger than this value, voting is allowed.
    "MinAverageDiffToAllowShuffle": 0,
    // If difference in standard deviation of skill is larger than this value,
    // and this value is greater than 0, voting is allowed.
    "MinStandardDeviationDiffToAllowShuffle": 0
}
```

An error message will be displayed when attempting to shuffle if the number of players on teams is large enough and the constraints aren't met.
