### ISSUE TITLE
"All talk is enabled" overlaps XP in Combat at low resolutions

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#686]
At vertical resolutions 1080px and below, the "All talk is enabled" notification overlaps the XP in the combat mod. See the attached screenshot.

![image](https://user-images.githubusercontent.com/29663681/39769696-ead6e020-52ba-11e8-83f7-28717f30df2f.png)

**Comment by Person8880** [comment]
The next update will add a new hook, `OnUpdateAllTalkText`. It receives 3 arguments:
1. A boolean indicating whether the text is currently visible.
2. The x position of the text (as a fraction of screen width).
3. The y position of the text (as a fraction of screen height).

The hook is expected to return values for the same properties it is passed, e.g.

```lua
function Plugin:OnUpdateAllTalkText( Visible, X, Y )
    -- Move the text up slightly from its default position at the bottom of the screen.
    return true, 0.5, 0.9
end
```

You could either bundle a small plugin with the combat mod to handle this or use `Shine.Hook.Add` directly, whichever you prefer.
