### ISSUE TITLE
FEATURE REQUEST: automatic reset and shuffle

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#688]
many times we run into issues where players change teams etc. after a shuffle.
simply locking teams into place is not feesible as often players need to swap to command etc.

What I'd like is for a feature where the server can check if teams are balanced at the 60 second mark and force a reset shuffle if they are not even. Many times players sit in "spectate" and see which team is stacked and then auto-join that team. Late joiners are also an issue but I think having something like this in place would solve a lot of early game balance issues.
Thanks for listening and keep up the awesome work!!! <3

**Comment by Rusty01** [comment]
When we have an admin on we force a shuffle and players are generally ok
with it. Could you perhaps instead of forcing a shuffle at the 60 second
mark, offer up a vote instead at the 50 second mark?
"teams are not even. Reshuffle game"?

**Comment by Rusty01** [comment]
There's a lot of new players and many of them are very very passive. They
won't start a vote on their own and most won't even understand that teams
are uneven. we're at a 40/60% win rate for marines vs aliens over 21,000
games and many of these are due to stacked alien teams. Shuffle does it's
job but late join stacks are happening a lot and most stacks happen within
the first minute.

**Comment by GhoulofGSG9** [comment]
To resolve the issue that new players often do not notice a ongoing shuffle vote I would make the vote more direct and use the vanilla F1/F2 Voting GUI. Maybe there should be an plugin option to utilize that GUI instead the shine menu.

**Comment by Person8880** [comment]
Avoiding forcing votes on players (as the NS2 vote UI does) is a conscious design choice that avoids one player being able to disrupt the entire server with votes.

If players are failing to understand that teams are imbalanced then having a shuffle vote pop up on them won't really improve the situation. The best you could hope for would be blind F1 pressing just to get the vote off their screen.

Most of the servers I've seen have some form of hint in their advert cycle to indicate how to open the vote menu, as well as the map vote telling players how to do it. If people don't then notice the shuffle button, or take note of the often vocal players advocating shuffles, I'm not sure anything will make them understand.

It would be possible to display a warning if teams are imbalanced after <x> time into a round (both in the chat and perhaps as something more prominent on the screen), but I still think it should be up to players to act upon it.
