### ISSUE TITLE
Shine Plugins are not updating (Error 32 trying to Open(CreateFileW))

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#689]
Hey Person8880

Something happened on my server (I believe a BSOD is the reason) and it causes my shine plugins to no longer update :(

Here is a snippet of the log:
[  3.430] Worker 00 : Error 32 trying to Open(CreateFileW) 'C:/Server/ns2server4/CONFIGURATION/shine/plugins/AFKKick.json'
[13:14:10]Error writing afkkick config file: config://shine/plugins/AFKKick.json: No such file or directory
[13:14:10]- Extension 'afkkick' loaded.
[13:14:10]- Extension 'approved' loaded.
[13:14:10]- Extension 'badges' loaded.
[  3.759] Worker 00 : Error 32 trying to Open(CreateFileW) 'C:/Server/ns2server4/CONFIGURATION/BannedPlayers.json'
[  4.087] Worker 00 : Error 32 trying to Open(CreateFileW) 'C:/Server/ns2server4/CONFIGURATION/shine/plugins/Bans.json'
[13:14:10]Error writing ban config file: config://shine/plugins/Bans.json: No such file or directory

The complete log can be found here: https://pastebin.com/BDn9qWYG I have tried to let Shine update the plugin by itself and then change it with same result: Error 32. 

I am using Windows 7 with the newest updates.

I am really helpless and probably it's not even a shine problem but my OS is messing up. Any help is welcome, thank you.

**Comment by Person8880** [comment]
As far as I can tell, error 32 means the file is locked by another process so can be read but not written to.

Is anything other than the NS2 server that you have that reads/writes to these files? Shine itself will close files as soon as it's done reading/writing so it shouldn't be locking them unless NS2's I/O doesn't implement file closing correctly.

**Comment by Wooza42** [comment]
I tried using Process Explorer and searched for "handels or dll" but it doesn't find anything. I will try later tonight and report

**Comment by Wooza42** [comment]
I found this when searching the string "ns2" in the Handle or DLL window:
<Non-existent Process>    6800    File    C:\Server\ns2server4\CONFIGURATION

I can't terminate that process and I will try to reboot the server once it's empty

**Comment by Wooza42** [comment]
So I tried rebooting the machine and check it again, with only NS2 starting and no monitoring / restart script. The error remains the same, plugins are not able to update. I have sent a screenshot with ProcessExplorer active, maybe you find something
![af](https://user-images.githubusercontent.com/19150896/40333526-2f1e7d6c-5d59-11e8-895d-abcfecf6ab50.png)

**Comment by Person8880** [comment]
It doesn't look like anything's locking the config files according to that list. Either the list is missing entries (is Process Explorer being run as admin?) or NS2 itself is locking itself out of the files despite them being closed after reading.

Might be worth also validating the NS2 server files if you haven't already to make sure they haven't been corrupted somehow from the BSOD you mentioned.

**Comment by Person8880** [comment]
I'm going to assume this is resolved given the lack of any further comments. Feel free to re-open if you still need help.
