### ISSUE TITLE
UseStrictMatching not working properly?

### ISSUE THREAD

**Issue by Laaas** [Person8880/Shine#690]
After a round on ns2_veilveil, ns2_veil_five popped up as an option for some reason. How come?

**Comment by Person8880** [comment]
Is `ns2_veilveil` a typo or is that actually the map name?

If it's a typo, bear in mind that the last map exclusion applies only to previously completed maps, not the current map. There's a separate option to consider similar maps as extensions of the current map (`ConsiderSimilarMapsAsExtension`) to prevent maps that are similar to the current map from showing up (if map extension is no longer permitted).

**Comment by Laaas** [comment]
Thanks!
