### ISSUE TITLE
AFK Plugin: AFK players on IP's won't get moved to the side anymore

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#693]
Hello,

In the past, Shine has moved AFK players away of the IP when they were idling on it. This seems no longer be the case. Would be nice to have this feature back. Thanks ahead!

**Comment by Person8880** [comment]
The plugin actually never used to contribute to this. The vanilla AFK check was running at the same time, tracking its own AFK time. Presumably one of your mods recently disabled that.

I've made the plugin override the vanilla timer now. Providing none of your other mods alter `AFKMixin:GetAFKTime()`, infantry portals should push AFK players away.
