### ISSUE TITLE
AFK Plugin: Misleading text when warning players.

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#694]
Okay, this is not the first time I mention this. I open another ticket since there is various people confused about the AFK plugin. 

Let's say we have following scenario of this setting: WarnMinPlayers: 12, MinPlayers 24.

Now, when the threshold of 12 players is reached, the AFK Plugin is moving the player to the RR AND is sending a warning text, that he gets kicked after x more minutes. This is the confusing part because as long as the MinPlayer value is not met, the AFK player won't get kicked. But when reading the text the player thinks he will be kicked. My recommendation therefor is to edit the text and include the MinPlayers parameter in so players understand when they are actually about to get kicked.

**Comment by Person8880** [comment]
This should be resolved. It will display something like:
> You have been AFK for over 5 minutes. You will be kicked if you are AFK for 10 minutes and the player count reaches 12.
