### ISSUE TITLE
AFK kick bug

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#697]
I was AFK kicked despite not being AFK. Even though it's set to strict for non-specs it shouldn't kick me since I moved just seconds before the kick, right?
Video: https://www.youtube.com/watch?v=MLB-HNlPpfM
Log (at 13:32:30): https://pastebin.com/t2Df8LsY
Config file: https://pastebin.com/CdSqme4y

**Comment by SupaFred** [comment]
I forgot to set the video to unlisted. You should be able to see it now.

It could be that it's working as intended but it felt wrong being kicked a second after I had moved so perhaps the strict mode could be tweaked a bit.

**Comment by Person8880** [comment]
Should be fixed by 39f369a7d73b27590924e46aae0ecaeabd4a034d in the next update. Any movement will immediately drop the time below the kick threshold.

**Comment by SupaFred** [comment]
Thanks!
