### ISSUE TITLE
Option to disable chat commands

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#700]
Could there somehow be an option to disable all chat commands, leaving only console commands?
My apologies if this option already exists somewhere.

**Comment by Person8880** [comment]
By disable, do you mean displaying an error if attempting to use them or letting all text chat through without any processing?

**Comment by TheRealNin** [comment]
Just letting all text through. An admin was typing "#reset" as a joke into the chat, thinking only !reset would do anything, and the whole game reset.

**Comment by Person8880** [comment]
Isn't the real fix to instead make the command matching stricter so it only matches `!` or `/`?

**Comment by TheRealNin** [comment]
That could work too.

**Comment by Person8880** [comment]
Solved in 7b8e25c995344aee8b5d511539ed594bb31b3a88. I have no idea why I decided long ago to match it so loosely. I'm surprised no one's mentioned this earlier.
