### ISSUE TITLE
Shuffle - Disable as soon as the round starts

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#702]
Hey,

Either I can't configure it properly or there is no setting: Once a round started people can still vote for shuffle for x seconds. I wish that a possible shuffle vote stops as soon as the round starts.

Thanks in advance for any help

**Comment by Person8880** [comment]
A bit awkward, but setting `BlockAfterTime` to a tiny, non-zero value, e.g. `0.001` will effectively block the vote when the round starts.
