### ISSUE TITLE
Getting forced into the wrong team in a new round

### ISSUE THREAD

**Issue by Vetinar1** [Person8880/Shine#705]
I frequently am forced to play in the team I don't wish to play as a new round starts. This seems to be indpendent of client preferences.

Reproduction steps:
1. Vote shuffle.
2. Finish match before shuffle enforcement expires. Server switches to new map.
3. Be the first to load the map. Attempt to join a team. (Via console commands or walking into the gates)
4. Shuffle will put you in a team, independent of the team you wanted to join and the fact that both teams are empty.
Specifically, I frequently try to join marines, only to be put on aliens "for balance", _despite both teams being empty_. This has _also_ occurred while my shuffle preference was set to marines.

**Comment by Person8880** [comment]
Shuffle enforcement doesn't persist after a map change. Sounds like the server might be running some other mod to enforce teams?

**Comment by Vetinar1** [comment]
I'll check with the admins once I get a chance.

**Comment by Person8880** [comment]
I've altered the behaviour of the shuffle plugin to avoid auto-assigning the first player to join a playing team. While I don't think it's applying in the case you're describing, it should cover it on servers that do use it.
