### ISSUE TITLE
[MapVote] [Suggestion] - Inform players better when nominating a map

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#706]
Currently when a player nominates a map it, either says that you have nominated the map for the vote, ot it couldn't be nominated for since it's not available.

Now with a more advanced mapcycle, you probably have criterias included which give additional condition if the map is shown in the mapvote or not. The player though has no idea about that and often wonders why his map won't show up.

My suggestion therefor would be that the player gets additional information and shine tells him about what other criterias must be met to display the map in the mapvote.

**Comment by Person8880** [comment]
Will be in the next update as:

> NOTE: {MapName} has conditions that may prevent it from being an option when the map vote starts.
