### ISSUE TITLE
[Request] - Disallow player using Reset vote

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#707]
Hey,

I have every now and then a troll which is using the reset vote in an abusive way and I would like this to stop.

I thought about creating for those trolls a group in the userconfig and then somehow there restrict access to the votes if it's possible. It already works great with them trying to kick someone since I give them a lower immunity the vote cannot start.

Maybe this can be even more expanded and configured to all different types of votes

**Comment by Person8880** [comment]
In the next update, deny the `sh_ns2_voteresetgame` permission from any groups you want to block the reset vote for. Other votes can be blocked in the same way, e.g.

* `sh_ns2_voteaddcommanderbots`
* `sh_ns2_votechangemap`
* `sh_ns2_votingforceeventeams`
* `sh_ns2_votekickplayer`
* `sh_ns2_voterandomizerr`
