### ISSUE TITLE
[Request] Notify players about commander changes

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#708]
I would like a feature of notifying players through chat text and the center of the screen about following:

- When a round starts, inform players about the commander's name
- When a commander has been replaced by another commander (no eject vote, manually leaving chair)
- When a commander has been ejected and replaced by another commander

Additionally it would be nice if Server Operations can create their own text and choose if they want it as chat message or in the middle of the screen or both.

**Comment by Person8880** [comment]
In the next update, the adverts plugin will have the following new events:

* `COMMANDER_LOGGED_IN`
* `MARINE_COMMANDER_LOGGED_IN`
* `ALIEN_COMMANDER_LOGGED_IN`
* `COMMANDER_LOGGED_OUT`
* `MARINE_COMMANDER_LOGGED_OUT`
* `ALIEN_COMMANDER_LOGGED_OUT`
* `COMMANDER_EJECTED`
* `MARINE_COMMANDER_EJECTED`
* `ALIEN_COMMANDER_EJECTED`

You can add the name of the commander in question to the prefix or message using `{CommanderName}`. Note that if a commander is ejected only the eject events will fire, not the logout events, and vice versa.

For example, this would tell the marine team that a commander has logged into their chair, with the name of the new commander displayed in yellow:

```json
"TriggeredAdverts": {
    "MARINE_COMMANDER_LOGGED_IN": [
        {
            "Prefix": "{CommanderName}",
            "PrefixColour": [ 255, 255, 0 ],
            "Message": "logged in to the command chair.",
            "Team": "MARINE"
        }
    ],
}
```

**Comment by Wooza42** [comment]
Thank you a lot!
