### ISSUE TITLE
[Bug] Rearranging the Chat windows is reset when not opened

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#710]
The chat box is reset to the vanilla place and when opened (pressing Y or Enter) being moved to the placed where the client has moved it.

**Comment by Person8880** [comment]
I'm not sure I follow exactly what you're saying. Are you saying the chatbox is resetting itself to the default position every time it's opened? Or that you don't want it to remember it?

It always remembers the last position it was at when I use it, which is what's supposed to happen.

**Comment by Wooza42** [comment]
Yes it is resetting itself to the vanilla position, and when opened again using the custom position. I can try to make some screenshots later

**Comment by Person8880** [comment]
I think I understand what you mean now. It's not a bug, it's never been able to move the outer chat text.

I've added an option to make it do so for the next update.
