### ISSUE TITLE
[Request] Mapvote - Hide total amount of votes during Mapvote

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#711]
It's very easy to change the outcome of a mapvote. The first 2-3 people who vote for a map will have a big advantage over other people who voted for another. People tend to vote for what people already voted for.

My request is that server operators can disable the amount of votes and that (optionally) the numbers may be shown after X seconds or so.

Thanks in advance!

**Comment by Person8880** [comment]
Is it really a problem if people do this? People are still making a conscious choice informed by the counts. I don't see the benefit in removing that information.

**Comment by Wooza42** [comment]
I have observed throughout the years that people rather for only 2-3 maps and that those 2-3 have a high vote activatity. I had 10 maps and now 8 maps available in the cycle and despite of the high voted ones, the others remaining with usually 0 votes. 

I would like a bit more diversity and try to let people vote for the map they like most not the one they would rather want to play because the other map with high votes is one they may not like so much.

Also I have observed that maps listed  at higher position have a higher vote activity than for example those at the bottom.

In addition to late voters will also be intrigued by the high cause, their vote is lost anyway so they vote for the second best map.

No worries, you can close it if you want. I just thought it would be nice if it's in the original shine mod instead of another plugin or mod.

Thanks in advance and to all other requests! Me and the NS2 server operators really appreciate it
