### ISSUE TITLE
Default abilities to reset/etc

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#714]
Per the new update "NS2 votes can now be blocked for users/groups by assigning permissions of the form sh_ns2_<votename>. See the wiki for a list."

Per this list: https://github.com/Person8880/Shine/wiki/Configuring-Users#special-access-commands all commands, save for one, are supposed to be allowed by default. That's not currently what's happening. Despite having no permissions set one way or the other, all commands are blocked from access.

I'm sure this is just an overlooked error, but I'm reporting it as it's preventing players from resetting, etc.

**Comment by Person8880** [comment]
I tested it against a config that had a default group, but forgot to test without one. I've uploaded a fix to the workshop, apologies for missing it.
