### ISSUE TITLE
[Suggestion] console command for client configs

### ISSUE THREAD

**Issue by Dreyal** [Person8880/Shine#717]
I would like a feature to change the shuffle team preference through a command in the console.
This would allow to bind the preference on the same key as joining the team someone tries to play on (j1,j2,rr), instead of changing it every few games in the client settings.

Loving your work Person and hope Shine wont ever die <3

**Comment by Person8880** [comment]
It already is a console command, `sh_shuffle_teampref <team>`, where team is either a name (`marine`, `alien`) or number (`1` or `2`).
