### ISSUE TITLE
Commander bans not working

### ISSUE THREAD

**Issue by Laaas** [Person8880/Shine#718]
Hey Person8880, I've noticed that people can command even if they've been commbanned. I've only noticed this for players who have been banned permanently, but it may apply to temporary bans too. Do you have any idea what could cause this? I see nothing in the logs, is there something specific I should search for?

**Comment by Person8880** [comment]
I can't seem to replicate this. When I ban myself either permanently or temporarily, I am correctly blocked from entering command chairs and hives with a message saying I'm banned from commanding.

Perhaps another mod has altered `CommandStructure:OnUse()` and overwritten the hook, or maybe the bans haven't loaded properly if you're loading remotely?

**Comment by Person8880** [comment]
I've just released an update that changes the point at which the ban is checked, and also adds some extra debug-level logging that you can turn on by setting `LogLevel` to `Debug. Give it a try and see if it helps.
