### ISSUE TITLE
[Bug] AFK Plugin - It remains a problem

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#719]
I have reported some odd behaviour already about the AFK plugin and I know now more:

For whatever reason it seems that sometimes the vanilla AFK system is active the same time Shine AFK plugin is. That results in people getting rather moved by the vanilla system  instead of Shine since the timers are different. I have attached a screenshot that shows clearly the vanilla text:

https://imgur.com/dt6OFw8

I also send my Shine AFK config and my serverconfig.json for verification. I had previously the vanilla settings on default and now replaced that with "0" in hope it would deactivate it but without success.

[Configs.zip](https://github.com/Person8880/Shine/files/2383952/Configs.zip)

**Comment by Wooza42** [comment]
Ok. Yes I was playing with the SampleIntervalInSeconds value a month ago or two to optimize the performance. My CPU can be found here: https://valid.x86.fr/wnnuva and it's a 7th gen Intel CPU. I am going to revert this and use the default value of 0.25.

I will observe this tonight again and give a feedback. I don't see though if this can fix the issue with sometimes the AFK timer popping up. Should I report this to UWE as well or could it be a config issue on my side?

**Comment by Person8880** [comment]
Your CPU is the same model as mine, but clocked significantly faster, so should be fine with the default sampling.

The vanilla message is used by the plugin when the minimum player count to start kicking is reached as it saves having to make a separate translated message for the same thing. I suppose I could change this to avoid it being confused for the vanilla version.

**Comment by Wooza42** [comment]
Thanks for the info. I report again about the AFK Plugin but I think this was it; that the SampleIntervalInSeconds is set too high. Thanks a lot!
