### ISSUE TITLE
Possible to bypass NameFilter

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#722]
I am trying to use the plugin NameFilter to prevent people from using my name on the server but it's possible to bypass it somehow. The player in the linked example log is bypassing both the name filter and my attempt to force him to use a certain name.

https://pastebin.com/Ug5PaB7c

**Comment by Person8880** [comment]
Should be fixed by 78440129f31781a6d22e0f01be20ba39d0cfb7e7 in the next update.
