### ISSUE TITLE
Idea: Commander notification when jumping into a hive

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#724]
hey,

I would like a plugin / mod that allows server operator to create a text that are basically describing the guidelines of commanding when someone jumps into the chair. This ofc only works with a game start delay (to be found in pregame plugin). This text should appear in the middle of the screen to get the comms attention.

This could even be optimized and add buttons into as well where the comm can accept or reject the guidelines. With rejecting ofc he gets ejected automatically. The selection should be saved for a while and maybe reappear again when text changes or a long time passed.

**Comment by Person8880** [comment]
Apologies for the (extremely) late reply @Wooza42, but is this something you're still interested in and haven't implemented elsewhere? If you are still interested, I might be able to include something in the update I'm working on at the moment.

My thinking would be to display a webpage with a configurable URL to the user, similar to the MOTD, but with accept/reject buttons added to it. A webpage is preferable here as the game doesn't deal with networking large textual data very well, and you'd be able to make something a lot nicer to read with a webpage than just text. It also then means the accepting guidelines can be remembered based on their URL.
