### ISSUE TITLE
Question - Shuffle preference

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#725]
hey,

I have observed (maybe it might be me only) that shuffle is a bit "too perfect", meaning that when I for example select alien as my prefered team, it tries to send me to aliens all the time when a shuffle occurs, even when manually went to marines before.

Maybe the shuffle preference should only be taken into account when you are not in a team already? Or is that difficult for the shuffle algorithm?

**Comment by Person8880** [comment]
This will be fixed in the next update by always assuming that a chosen team is the player's current preference (i.e. using the console or walking through a team door will set the preference).
