### ISSUE TITLE
Feature request: Visibility of gags and gagids similar to bans/commbans

### ISSUE THREAD

**Issue by AlexJFox** [Person8880/Shine#726]
Gagging is a great feature and on TA we use it in lieu of banning people wherever possible, however currently gagging isn't supported in the admin menu and there is no way I'm aware of to list the current gags that are active. Is it possible for this information to be printed into a tab in the admin menu or at least for an sh_listgags command to be implemented?

Thank you!

**Comment by Person8880** [comment]
The next update will have a `sh_listgags` command.

**Comment by AlexJFox** [comment]
Thank you so much!
