### ISSUE TITLE
AFK plugin Idea: Auto-AFK after mapchange.

### ISSUE THREAD

**Issue by pSyk23** [Person8880/Shine#729]
Issue:
Currently there are always a few players afk after mapchange, but they aren't tagged afk until the set time has reached.
Thus they are shuffled into teams and rounds start with 1-4 players being afk in base.
This leads to uneven teams, bad round starts, reset votes, re-shuffles and overall frustration.

Suggestion:
Mark every player AFK immediatly after mapchange until they move to filter out everyone "taking a break / doing stuff" during mapchange.
Everyone not moving after mapchange will be AFK and not considered for shuffles.

**Comment by Person8880** [comment]
Shuffle should treat players that haven't moved since joining as AFK regardless of how long they've been idle in the next update.
