### ISSUE TITLE
Shuffle throwing the entire server into the ready room.

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#731]
It looks like, while the new function of shine is working as far as not putting idle players into teams, it is also throwing the entire server into the ready room. It seems to always happen after a map change, and for the first shuffle.

Could we look into putting an option in to disable this new function? It currently seems to be causing more harm than good.

I should clarify: Map changes > Players that are active join a team and vote for a shuffle > Shuffle vote passes > Players that are already on a team are thrown into the ready room instead of being shuffled.

**Comment by Person8880** [comment]
I can't reproduce this. Are you using anything that would alter how the `afkkick` plugin works?

**Comment by TA-Red** [comment]
Correct, I did have a delay set. Thanks, I'll report back if it continues. As always, I appreciate all of your efforts!
