### ISSUE TITLE
FEATURE REQUEST: Improve round start implementation

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#732]
I would like to request a feature to prevent commander tasks from being performed, until both teams obtain a commander. This would allow the round to start without two commanders if necessary. A time-out variable would be helpful, to set the maximum wait time, if one team never gets a commander.

I can think of a basic implementation to block chair and hive entrance, but there may be a better solution. Before the match starts, it's possible to enter these objects without performing any tasks.

This would eliminate unnecessary down time when resetting the match or starting a new game. Players would also be able to start the match, without the dreadful of task of waiting for two commanders. 

The most common reason for resetting is because one team starts building, before the other gets a commander. This would drastically cut the number of required vote resets, if implemented properly.

**Comment by Person8880** [comment]
I'm not sure I see how this will help. If both teams don't have a commander, starting the round but blocking commander actions would be very confusing for the team with a commander.

It basically amounts to not wanting to start the round (as nothing can be done if the commander can't build), in which case why pretend to start it?

**Comment by stickz** [comment]
Most servers do not wait for two commanders to start. It may be more preferable in this instance, to add an optional feature: `"Please wait 30s or until both teams have a commander before placing structures."` This would prevent the need for a round reset and reduce down-time players experience between map changes. It would also allow the round to start quicker, knowing this safeguard is in-place.

Currently, rounds are constantly vote resetting because 1 team doesn't get a commander in the first 30-60s. The necessity to perform this action, can be mitigated by a better round start implementation. It doesn't have to block all commander actions, it could just stop resource towers/harvesters to prevent a resource advantage from developing over this conflict. Perhaps, a config var should define what to block.
