### ISSUE TITLE
[Locale] Tiny mix in locale/shine/extensions/voterandom/enGB.json

### ISSUE THREAD

**Issue by axamdy** [Person8880/Shine#734]
I recently realized that the Vote Random has been updated, so I plan to update the Chinese localization too.
Then I found this:
`locale/shine/extensions/voterandom/enGB.json`
```json
127:|    "AUTO_SHUFFLE_ENABLED_RANDOM_BASED": "Automatic score based teams have been enabled.",
128:|    "AUTO_SHUFFLE_ENABLED_SCORE_BASED": "Automatic random teams have been enabled.",
```
Obviously.

**Comment by Person8880** [comment]
Ooops! Thanks for reporting, it's fixed now.
