### ISSUE TITLE
Clients get "invalid data" since the update tonight

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#737]
https://www.dropbox.com/s/shmulr5gajgcsoe/log-Server.txt?dl=0
Server log.

**Comment by AlexJFox** [comment]
No clients can connect to TA servers after this update either...

**Comment by Person8880** [comment]
Looks like a 3rd party plugin that's adding a hook in an unexpected place. I've just pushed an another update that should fix it.

**Comment by stickz** [comment]
`[ 11.586] Worker 00 : Error: lua/shine/core/server/logging.lua:55: attempt to index field 'Config' (a nil value)
[Server] Script Error #1: lua/shine/core/server/logging.lua:55: attempt to index field 'Config' (a nil value)`

**Comment by SupaFred** [comment]
Thank you for the quick fix. It's working again.

**Comment by AlexJFox** [comment]
Thanks for the quick response!
