### ISSUE TITLE
FEATURE REQUEST: StartDelayInSeconds variable for shuffle votes

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#738]
I would like to request a feature where shuffle votes can't be started in the first x number of seconds after map start. Players are currently shuffling before everyone has a chance to connect to the server.

This variable should have a default value of 30 seconds to reflect bare minimum connection time.

**Comment by Person8880** [comment]
This will be added in the next update as `BlockUntilSecondsIntoMap` (defaulting to 0 to avoid changing current behaviour as some server operators may not want it).
