### ISSUE TITLE
FEATURE REQUEST: Improve server ban functionality

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#740]
I would like a feature which allows people who are banned from the server to connect. Then the player should to be notified about being unable to leave spectator. I would also like an optional setting which prevents them from using server chat or microphones. And anther to allow RR access at round end.

The purpose of this feature is allow banned players to spectate and see what they're missing by misbehaving. I think tormentation is a effective forum of negative punishment. Not allowing a person to play removes the negative stimulus they can't handle and teaches them how to behave without it.

**Comment by Laaas** [comment]
`I would also like an optional setting which prevents them from using server chat or microphones.` this is already possible through the permamute plugin.
The first part about disallowing them from playing is interesting, and is surely implementable.

I don't think your motivation is right at all though lol.

**Comment by stickz** [comment]
A server moderator would have to deal with them twice, if not automatically gagged and muted on ban. They may prefer to automate this process and make ghosting much more difficult while doing so.
