### ISSUE TITLE
FEATURE REQUEST: Ability to be in multiple groups

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#743]
It probably sounds weird when reading the title but basically I would like an option where I can add players which are already in a group to another group.

Background: So it may happen that I want to add a player that is already in a group (e.g donation group) to another group (stacker group) and optimally use the lower immunity and restrictions if available.

Assuming I have a player that is in a donation group, and I want to add him to the stacker group; this would be my two groups:

"DonationMember": {
        "IsBlacklist": false,
        "Immunity": 5,
        "Commands": [ "sh_listmaps" ],
        "Badges": { "1": [ "Donation" ], "2": [   ]}
        },
"StackerGroup": {
        "IsBlacklist": false,
        "Immunity": 3,
        "Commands": [{ 
		"Command": "sh_unstuck", 					"Denied": true, 
		"Command": "sh_ns2_voteaddcommanderbots", 	"Denied": true,
		"Command": "sh_ns2_votechangemap", 			"Denied": true, 
		"Command": "sh_ns2_votingforceeventeams", 	"Denied": true, 
		"Command": "sh_ns2_votekickplayer", 		"Denied": true, 
		"Command": "sh_ns2_voterandomizerr",		"Denied": true,
		"Command": "sh_ns2_voteresetgame",			"Denied": true
		}, 
		"sh_listmaps"],
        "ForcedBadges": { "1": ["stackerbadge"], "2": [ ]}
        },

Maybe there is another way; the only one I come up now is to clone every existing group and add the info for the stackergroup to the newly generated group, like this:

"DonatorButAlsoStackerGroup": {
        "IsBlacklist": false,
        "Immunity": 3,
        "Commands": [{ 
		"Command": "sh_unstuck", 					"Denied": true, 
		"Command": "sh_ns2_voteaddcommanderbots", 	"Denied": true,
		"Command": "sh_ns2_votechangemap", 			"Denied": true, 
		"Command": "sh_ns2_votingforceeventeams", 	"Denied": true, 
		"Command": "sh_ns2_votekickplayer", 		"Denied": true, 
		"Command": "sh_ns2_voterandomizerr",		"Denied": true,
		"Command": "sh_ns2_voteresetgame",			"Denied": true
		}, 
		"sh_listmaps"],
        "ForcedBadges": { "1": ["stackerbadge"], "2": [ ]},
        "Badges": { "1": [ "Donation" ], "2": [   ]}
        },

**Comment by Person8880** [comment]
Group inheritance should cover this:
```json
"DonatorButAlsoStackerGroup": {
    "Commands": [],
    "IsBlacklist": false,
    "Immunity": 3,
    "InheritsFrom": [ "StackerGroup", "DonationMember" ]
}
```

Also, your commands in `StackerGroup` aren't quite right, each entry needs its own brackets:
```json
"Commands": [
   { "Command": "sh_unstuck", "Denied": true },
   { "Command": "sh_ns2_voteaddcommanderbots", "Denied": true },
   { "Command": "sh_ns2_votechangemap", "Denied": true },
   { "Command": "sh_ns2_votingforceeventeams", "Denied": true },
   { "Command": "sh_ns2_votekickplayer", "Denied": true },
   { "Command": "sh_ns2_voterandomizerr", "Denied": true },
   { "Command": "sh_ns2_voteresetgame", "Denied": true }
],
```

**Comment by Wooza42** [comment]
Thanks a lot.

Is there a command where I can change players group, or do I have to use manually the userconfig.json? I couldn't find anything in the wiki (basecommands article)

**Comment by Person8880** [comment]
Yes, the user management plugin has various commands for managing users and groups:
https://github.com/Person8880/Shine/wiki/User-Management
