### ISSUE TITLE
[Bug] Tornament mode plugin currently broken

### ISSUE THREAD

**Issue by Tikzz** [Person8880/Shine#745]
We have been using the tornamentmode plugin for a while now in our server, but since the last couple of weeks (don't remember exactly, sorry) it's broken.

Client console output: https://i.imgur.com/YtUiSZI.jpg
https://github.com/Person8880/Shine/blob/master/lua/shine/extensions/tournamentmode/client.lua#L30
Seems like StringFormat is not defined in client.lua

Also the !ready/!rdy functionality stopped working, so maybe there are more errors present in the server part of the plugin.

**Comment by Person8880** [comment]
This should be fixed in the next update.
