### ISSUE TITLE
FEATURE REQUEST: Discord Chat Integration

### ISSUE THREAD

**Issue by Azperin** [Person8880/Shine#749]
Is it possible to send public chat messages to some http server (with discord bot with it to proxy msg) ? And most important is there some methods to recieve messages from outside the game ? If someone post anything in specify discord channel, it appear in the game (like notyfy system messages but with nickname). 
How i see it might look like:
Hook to client send public message -> Shared.SendHTTPRequest to some endpoint (config). Any errors, working endpoint, etc ... not intereting us. Fire and forget.
On the HTTPserver side, we get message with discord-bot from channel and send to ns2server -> then broadcast it to clients on the gameserver.
Hope you get the idea.

**Comment by GhoulofGSG9** [comment]
There is already a third party solution to connect your discord server and ns2 server in-game chat. Have a look at https://github.com/eBrute/ns2-discord-bridge

**Comment by Laaas** [comment]
there is also my version, https://github.com/Laaas/ns2-discord-bridge and https://github.com/Laaas/ns2_discord_bridge_mod/, although I warn you, it is a bit buggy! Specifically, it does not handle the server restarting well (and often crashes in that case) on Windows. If you're using Linux it's no problem IIRC.

**Comment by Laaas** [comment]
You may want to use my version instead because it can handle many more messages, since it does not use constant HTTP polling.
