### ISSUE TITLE
REQUEST: sh_customvote prefixes all votes with "POLL: "

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#751]
Custom voting is a fun feature but can easily be confused with a "real" vote. It would be nice if it was more obvious to users when a custom vote is just a poll by a server admin.

**Comment by Person8880** [comment]
Will be in the next update as the `CustomVotePrefix` option, defaulting to "POLL: ".

**Comment by TheRealNin** [comment]
Great, thanks!!
