### ISSUE TITLE
[Bug] MapVote - ConsiderSimilarMapsAsExtension does not work

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#752]
Hey,

So I enabled this feature "ConsiderSimilarMapsAsExtension" but somehow maps that have a similar still occur in the mapvote. I set ExcludeLastMaps Min and Max to 4 so I understand that the similar maps also don't show for the next 4 maps, but they do, somehow.

An example would be: ns2_veil and ns2_veil_five, or ns2_veilveil which can show up.

**Comment by Wooza42** [comment]
Update:
Las said to me this:
> play ns2_veil
> then you can't play ns2_veil_five, because it's an extension
> play some other map
> now you can play ns2_veil_five since it isn't an extension and isn't one of the last 4 maps

I thought that ConsiderSimilarMapsAsExtension would remove the similar maps as long as the ExcludeLastMaps is set higher than 0

**Comment by Person8880** [comment]
`ConsiderSimilarMapsAsExtension` applies to the current map only when determining if a map is an extension of the current map. If you want to exclude similar previous maps, set `ExcludeLastMaps.UseStrictMatching` to `false`.

**Comment by Wooza42** [comment]
Thanks, this solved it
