### ISSUE TITLE
welcomemessages crash server with Rebirth Bots

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#753]
No idea how this is possible, but somehow welcomemessages is trying to send bots from Rebirth Bots some kind of welcome message and it crashes the whole server. Not just script errors, hard reboot.

Errors found at the end of logs before the reboot: 
https://pastebin.com/AaAQCvDn
https://pastebin.com/4e6yKtnt

**Comment by Person8880** [comment]
The real problem is something is calling `Server.DisconnectClient` on a `ServerClient` that's already disconnected. Are your bots based on older NS2 bot code? The vanilla bot code used to hold onto bots that had been removed already resulting in similar issues.

**Comment by TheRealNin** [comment]
Perhaps, I will look into it.
Thanks for the help!
