### ISSUE TITLE
Add option to shuffle to force AFK players in ready room to get shuffled

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#754]
After a game or after map switch, we have a lot of players in the ready room who are still ready to play but went to grab a drink or whatever. Shuffle happens while they are gone and they don't get put on teams. Is there a way to disable this without disabling the AFK plugin? If not, could a feature like this be added?
Thanks!

**Comment by Person8880** [comment]
This will be in the next update as the `RemoveAFKPlayersFromTeams` option. Set it to `false` to allow AFK players to be placed on teams.
