### ISSUE TITLE
Custom Skins

### ISSUE THREAD

**Issue by tsKenneth** [Person8880/Shine#758]
Hello, how do i change the default GUI skin applied to all clients without changing the skin in default.lua? I have created a seperate .lua in skins folder. Thanks love your work <3

**Comment by tsKenneth** [comment]
Found the command, just run:
Shine.GUI.SkinManager:SetSkin(SkinName)

**Comment by Person8880** [comment]
Ideally you should not be trying to change the default skin. If you want your UI menus to look different, apply a skin to them separately (e.g. like the chatbox does).

In the next update skinning should be easier, as you'll only need to set the skin on the root window element to have it apply to everything below. Also, the default skin will be an option in the client config menu and all the various issues I could find when changing it have been fixed.
