### ISSUE TITLE
Question: GUI Alpha

### ISSUE THREAD

**Issue by tsKenneth** [Person8880/Shine#759]
Hello, is it possible to apply transparency to GUI elements (i.e. panels)?

**Comment by Person8880** [comment]
Yes, colour objects have an alpha component (between 0 and 1 like the red/green/blue components). You can either specify it when constructing them as the 4th argument, or otherwise change it on an existing colour using the `a` field.

**Comment by tsKenneth** [comment]
thank you, got it :)
