### ISSUE TITLE
Merge ban, commban, and gagid functionality

### ISSUE THREAD

**Issue by AlexJFox** [Person8880/Shine#761]
_This seems like a significant request/change, for that I apologise._ 

I would like permanent bans and commbans to be handled by the existing bans system, as a different "type" of ban.

This would enable all server ops to run a true multi-server setup without relying on error-prone file scripts to synchronise configs.

Using webconfigs for commbans and gags is of course possible, but not without a fair amount of php knowledge.

Hopefully if you are able to accommodate this request, NoM may consider updating his PHP bans script to handle these new ban "types".

Thank you for considering!

**Comment by stickz** [comment]
Web configs are not designed to handle the permanent storage of large amounts of data. I would highly recommend allowing the server operator to point to a MySQL database for storing this information.
