### ISSUE TITLE
Badge issues

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#765]
I suspect with the latest patch 328 and all the UI changes that came in this patch, something may have gone the wayside in how Shine assigns badges. I’m not sure what more information I can give other than it appears to randomly map badges to players rather than the ones assigned in UserConfig.json.

Please let me know if there’s anymore information I can provide.

**Comment by Person8880** [comment]
Are there any warning/error messages after a map load from the badges plugin? Are you running any mods that could alter how the badge system works?

As far as I can see the badge code wasn't changed in build 328, and my local testing seems to assign badges correctly.

**Comment by TA-Red** [comment]
Found the issue - apologies. I’ll cascade the solution to the rest of the server ops who use the plugin so they don’t open another ticket.

The user simply has to add all vanilla badges to their badge pack in order to make it work correctly.

Thanks you either way!
