### ISSUE TITLE
Reserved Slots Issue

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#769]
Hi Person8880. Thank you again for the great work you do. We have a major issue at the moment and hoping you can help us.

The issue we have is with how reserved slots work now that we must have a max playercount of 20 to retain whitelisting.
Many games we end up with 10v8 or 10v9 and no-one from spectate can join because of those two reserved slots. Would we be able to change how reserved slots work altogether? One idea I had was that instead of setting the number of reserved slots in a config, we simply just assign a permission to users. From here when shuffle goes through - take anyone with a reserved slot out of spectate and put them into game. This way it would always be 10v10 and if someone left mid game, anyone without a reserved slot would be able to join from spectate. 

Is this a possibility? It would make a LOT of people very happy. 
Thanks!
~Rusty

**Comment by Person8880** [comment]
The closest to what you want right now would be:
* Change `SlotType` to `"ALL"`
* Change `Slots` to be less than or equal to the number of spectator slots (or 0 if you don't want to reserve any).
* Use @GhoulofGSG9's ready room queue plugin, which prioritises players with reserved slot access (`sh_reservedslot`).

**Comment by Rusty01** [comment]
Thanks. I'll give that a go.
