### ISSUE TITLE
Feature Request (May exist?) - Combination of round/timelimit map vote trigger

### ISSUE THREAD

**Issue by tkdavies525** [Person8880/Shine#774]
Hi,

I would like to configure the Shine Map Vote options to trigger based on both timelimit as well as max round options.

For example, say a timelimit of 30 minutes with max round limit of 2 is set. If 2 rounds are completed on a map with a total combined play time of 20 minutes, a map vote is held (based on rounds). Likewise, if one round is completed with 40 minutes of playtime, a map vote is held (based on the timelimit).

I may be missing something, but from what I can tell something like this is currently not possible as you can only have one or the other. Is it possible to implement this if it does not exist? And if it does exist, how would I go about configuring this properly?

Thank you as usual. :)

**Comment by Person8880** [comment]
This should be how it behaves already. When a round ends it checks both the time remaining (according to the map cycle's `time` field or a map's specific `time` value) and, if `RoundLimit` is greater than 0 (or a map has a `rounds` value), the number of rounds that have been played so far. If either the time has passed or the round limit has been reached, it will trigger a map vote.

Thus all you need to configure is both an appropriate maximum time, and a maximum number of rounds.

**Comment by tkdavies525** [comment]
Perfect, I was not using this before but it does work now that I'm trying it. The description on the wiki page was misleading about this setting so I did not bother to try it. Thank you for updating that too, it's much more clear now. A QoL implementation for stating the number of rounds and time left would be great too!

Thank you!
