### ISSUE TITLE
AFK system conflicting with Reserved Slots

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#778]
Hi, at the moment we have 2 public slots and 3 reserved slots setup for spectator. It's working really well. The problem we have is that when a player goes AFK, the AFK system is told to send that AFK player from game/lobby to spectate. If there's no available spectator slots than the player becomes unkickable (their name won't even show in the vanilla vote kick menu ) and requires an admin to remove them from the game. The quickest fix is for me to set the AFK plugin to kick instead of trying to move to spec. But was wondering if there's any workaround possible? Ex. If there's no room to place them on spec, then kick. I've attached a video so you can see what I mean.
Thank you again for everything. I love shine so much! 👍 

https://drive.google.com/file/d/1piPDx_1OLlssy0gufUOZVbx1znL8DC58/view?usp=sharing

**Comment by Rusty01** [comment]
There's nothing in the logs about warn or error. And although the
afkkick.json is set to move players to spectate, it also seems to be
kicking them.

**Comment by Person8880** [comment]
Your config's not valid JSON, so it's loading the default configuration which has no warning actions.

This part:

```json
  "WarnActions": {
        "NoImmunity": [MOVE_TO_SPECTATE],
        "PartialImmunity": [MOVE_TO_SPECTATE]
    },
```

should be:

```json
  "WarnActions": {
        "NoImmunity": ["MOVE_TO_SPECTATE"],
        "PartialImmunity": ["MOVE_TO_SPECTATE"]
    },
```

**Comment by Rusty01** [comment]
Good catch, thanks.Any idea on why people can't be kicked / people marked
as AFK not showing up in vanilla vote kick list?

**Comment by Person8880** [comment]
Is there definitely a link between people that are AFK and those not showing in the list?

I can see a potential bug in the game's code around how it updates the scoreboard player list which could explain the issue, but nothing in my code that would cause it.

**Comment by Rusty01** [comment]
100% only those that are marked as AFK are in that list.
Also it was only one server where I forgot the quotes in the "move to spectate". I was trying different options to see if it was a config issue on my end, but it's beyond anything I can fix unless I set it to actually kick the players from the server. My guess is that it could be attempting to move the player from ready room to spec, but due to there not being any available slots, they get stuck, and the entity remains.

**Comment by Person8880** [comment]
After some more digging I've found another reason for the kick menu to be missing players. The new game menu has a bug where the first entry of the vote kick list isn't sized correctly and thus is effectively invisible. This means there's always one player missing from the list.

Combine that with the other bug I found and there could be multiple players missing from the list at any given time. The fact they're AFK is purely a coincidence as it happens regardless of their AFK state.

As for the spectator moving, are you absolutely certain your config is correct and loading properly? As there's nothing that stops a player joining the spectator team (barring some other mod conflicting) regardless of the spectator slot count. I can sit in a server with no spectator slots at all and it moves me to the spectator team fine.

**Comment by Rusty01** [comment]
[AFKKick.txt](https://github.com/Person8880/Shine/files/3800892/AFKKick.txt)
The log file is indicating that AFKKick is kicking people and I see the players disconnecting. (It's not moving them to spectate). I'll set the log level to "debug" as you suggested and see what it captures. Thanks.
