### ISSUE TITLE
Steamworkshop API returns no url for downloading

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#780]
The steam download is broken. I guess it needs a republish. Thanks you.

e.g: http://steamworkshop.download/download/view/117887554
> Steam Api doesn't return the URL to download the file +_+

![image](https://user-images.githubusercontent.com/1570625/69362272-7ec5c100-0c8e-11ea-9af5-ae0607dad90b.png)

**Comment by Person8880** [comment]
Bizarre. Another workshop downloader website let me download it fine, but it's clearly been wiped for some reason by Steam.

I've just published a new version which seems to be stored correctly, hopefully this is a one off random problem on Steam's end.
