### ISSUE TITLE
[Vote Random] Enforce configuration based on playercount

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#782]
When server is not full <2/3 I would prefer to not BLOCK_TEAMS, I only want that when the server is almost full; would it be possible to support that somehow?

Overal, for all configs - it would be nice to set options based on playercount. Or maybe a "variable" if the server is in "seeding" mode.

Thanks you.

**Comment by Person8880** [comment]
The next update will let you control min/max player counts to apply shuffle enforcement policies, e.g. this would set a minimum player count of 14 (and no maximum):

```json
"EnforcementPolicy": [
    {
        "MaxPlayers": 0,
        "MinPlayers": 14,
        "Type": "BLOCK_TEAMS"
    }
],
```

As for changing other configuration values, it's hard to make a generic system as each plugin will have different ways that it uses the configuration values (e.g. some will read once when enabled, others read from the config every time they make a decision). Are there any particular values you wanted to change?

**Comment by ailmanki** [comment]
I wanted to disable bots when enough players are around, else:
- AFK length, shorter with less players
- Adverts, "server full, players will be kicked when afk" - only when max is reached - well just an example

**Comment by Person8880** [comment]
I've added an option to the AFK kick plugin in the next update that allows setting the warn/kick times based on player count rules, e.g. this would mean warn time is 1 minute and kick time is 5 minutes when there are <= 10 players on the server:

```json
"TimeRules": [
    {
        "MaxPlayers": 10,
        "WarnTimeInMinutes": 1,
        "KickTimeInMinutes": 5
    }
]
```
For player counts not covered by the rules, the existing time options apply.

As for adverts, in the next update both advert streams and individual adverts will accept `MinPlayers` and `MaxPlayers` values that constrain when they can display, e.g.
```json
"Adverts": [
    {
        "InitialDelayInSeconds": 10,
        "IntervalInSeconds": 30,
        "MinPlayers": 20,
        "Messages": [
            {
                "Message": "This displays only when there are at least 20 players on the server."
            }
        ],
        "RandomiseOrder": false
    },
    {
        "InitialDelayInSeconds": 10,
        "IntervalInSeconds": 30,
        "Messages": [
            {
                "Message": "This displays all the time."
            },
            {
                "Message": "This displays only when there are at most 10 players on the server, otherwise it's skipped.",
                "MaxPlayers": 10
            }
        ],
        "RandomiseOrder": false
    }
]
```

As for bots, the vanilla system should already get rid of them as players join teams.
