### ISSUE TITLE
Shuffle removes bots and never adds them back

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#786]
@Person8880 There's an issue with shuffling. If the server population starts to die off, the bots remain removed and require a map change to add them back. Could you add a configuration variable to re-add bots after the on-team player count declines to a certain number?

**Comment by Person8880** [comment]
Setting `BlockBotsAfterShuffle` to `false` in the next update will allow bots to join teams after a shuffle if the player count is low enough.
