### ISSUE TITLE
AFK kick kicks players between rounds

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#790]
I've configured the afkkick plugin to not kick players between rounds ("OnlyCheckOnStarted": true) but it's still active between rounds.

My afk kick config: https://www.dropbox.com/s/k3ddwrp28zy6yx8/AFKKick.json?dl=1
A kick between rounds at 23:01:02: https://www.dropbox.com/s/bxgy388cbipiqp6/2019-12-26.txt?dl=1

Is it a bug or have I configured it wrong?

**Comment by Person8880** [comment]
This is an oversight with the `KickOnConnect` option, will be fixed in the next update.

**Comment by SupaFred** [comment]
Thanks.

**Comment by SupaFred** [comment]
Could there be a similar problem with MinPlayers? I've noticed it kicking people when the player count has been below the value set in MinPlayers.

**Comment by Person8880** [comment]
Unless your `MinPlayers` value is more than the total number of player slots on your server, it shouldn't be possible for it to kick anyone below it.

The connection event only checks for someone to kick if all player slots are in use, regardless of `MinPlayers`. In this case, `MinPlayers` is only used to control when warnings are applied.

**Comment by SupaFred** [comment]
I've set MinPlayers to 25 on a server with 20 player slots and 6 spectator slots. I want it to not kick players at all until almost all slots are taken. Should I change MinPlayers to 19 instead?

**Comment by Person8880** [comment]
I've changed the logic to allow it to use `MinPlayers` if it's in the range of `[<max player slots>, <max player slots + max spectator slots>]`, so your value of 25 should start working in the next update.

**Comment by SupaFred** [comment]
Perfect. Thanks a lot!
