### ISSUE TITLE
[Request] Add logging for alien commander structure destroy.

### ISSUE THREAD

**Issue by Squirrelies** [Person8880/Shine#791]
Currently shine logs when a Marine commander recycles structures but Alien commanders have this ability as well but shine does not appear to log it. Can this be added?

Test steps:

Hop into the hive.
Create structures such as shells or harvesters.
Select structure and choose destroy.
Observe shine logs.

**Comment by Person8880** [comment]
The next update will add the `LogConsuming` option (defaulting to `true`) which will log when Alien buildings are consumed by the commander in the same manner as recycling. I've also updated the logs to show when recycling/consuming is cancelled too.
