### ISSUE TITLE
Feedback on the chat ui changes

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#800]
Thanks for the nice update to the chat/chatbox ui! It looks better and will make it easier to quickly read the chat.

I've noticed that several players are confused about where to find the settings for the ui. The separation of settings in the client config and the chatbox (under the gear icon) is not completely intuitive. It's also not obvious that you can scroll down in the list of options when you have opened the chat box settings. 

I don't really have an idea how to fix this. I just wanted to give some feedback on the problems I've heard some people have. Perhaps all of the chat/chat box settings could be in the client config menu instead?

**Comment by Person8880** [comment]
I did wonder if the settings would be unclear. I added a hint the first time a message is displayed, and added an entry in the main menu to try and make it more visible. 

I've now made the scrollbar permanently visible in the chatbox settings, and added a button at the bottom to open the chat settings in the client config menu. Merging the chatbox and chat settings could make sense, though I've always thought it convenient to have the chatbox settings available without having to go into another menu.

**Comment by Person8880** [comment]
I had another pass at this and instead of removing the chatbox settings menu, I've added the settings for the chat HUD to the chatbox's settings menu as a second tab. That way the settings are in one place and the convenience of the chatbox settings is preserved. Hopefully it will help avoid confusion in the future.
