### ISSUE TITLE
Massive Crashes

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#805]
Hi Person8880,
So for the last two days, I've been getting really bad crashes - every 15 minutes or so across my servers, there's also almost an intermittent "red plug" that happens every few minutes where pings spike and the client console spams "https://cdn.discordapp.com/attachments/124663337068789760/681736662015016999/20200225002943_1.jpg". At this time the game might resume, or the server might crash. It is almost always guaranteed to crash at map change.
[log-Server-2.old.txt](https://github.com/Person8880/Shine/files/4248282/log-Server-2.old.txt)

I haven't changed anything locally, and our servers haven't crashed in a really long time. Shine was the only item that updated. I know it's also affecting other servers as well just not nearly as bad as us. I'm not sure what to do.  Even now I am trying to start the server but it's caught in a loop of some kind ( see attached log ).  (Running Shine / NS2+ Vanilla with basic useConfig - no fetches from the web)

I'm not sure if you are able to roll back the latest update to shine to see if the issue resolves, but if you could do that - even purely so I can test that would be great.

*All my servers are doing the same thing. - same log file being created. - server is crashing on it's own and rebooting, crashing, rebooting.

**if I remove the plugins for shine, the server does work, but it does eventually crash. We do NOT get the red plug at map change. Crash still happens every now and then.

**Update. ok so all of a sudden all three servers started working like the issue never happened. Almost like the calm in a storm. It's weird as these servers are at different locations. And over the past two days it's been literally non stop red plug / crash.  But for the last two hours - smooth. Not a single red plug appeared even with all custom plugins loaded.
I hate to bug you for nothing, just this last two days has been crash after crash. I would still feel better if you rolled back. But I don't know. It's so hard to troubleshoot. :/

**update - server just crashed at map change. - 30 mins after my last message.

**Comment by Person8880** [comment]
From the log, it looks to me like the server is trying to download mods from the Steam workshop and is making no progress at all, which would seem to be a bug in the game's handling of mods. 

Presumably the update to Shine triggered it simply because it has to download a new version, though the logs seem to suggest it's already downloaded it (given the timestamp matches the last upload time). As it's never getting past the mod downloading phase it's not anything in Shine or any other mod causing it as it never even started to execute their code yet.

I'd bring this up with the NS2 devs if you haven't already.

**Comment by Rusty01** [comment]
Hi, thanks. 
Last night was just a mess with logs as it kept over-writing. I was basically removing plugins, testing, restarting etc. etc. But take a peak here.
http://www.diamondgamers.net/224
Two dumps with client and server log - one was when i was idling alone in the ready room, one was when the map was changing. Also I am using the advanced chat plugin. It's nice :) Just wish you could set the transparency level of the individual messages coming in. 

Also a strange issue too that I could never resolve. For some reason ( before and during the usage of the chat plugin, issue is month+ old) messages are delayed by about 8 seconds at times. Any idea what could cause that? It only happens in one particular location and happens to everyone even on a fresh server running vanilla shine and NS2+. It's annoying to say the least.

**Comment by Person8880** [comment]
Hmm, the logs don't seem to show anything particularly obvious or consistent between the 2 crashes. The dump files probably provide more clarity as to what's crashing, but only people with engine access can make good use of them (all I can see is it crashes in `lua51.dll` somewhere).

Messages being delayed would imply there's a backlog of reliable network messages that are taking a long time to be received and acknowledged. Reliable messages would only affect the peripheral features like chat, notifications and menu actions, not the game movement. I don't have enough knowledge about how the game's reliable networking system works to be able to know for sure what could cause it beyond something like a degraded connection dropping packets.

**Comment by Rusty01** [comment]
Apparently the issue was with logging according to the devs. I disabled logging in the baseConfig.json and it has resolved the issue.

**Comment by Person8880** [comment]
Did they say exactly why it crashed? Were the log files too large? Is it something they're going to fix? Logging shouldn't really be crashing the server (though the current logging could be optimised somewhat, even in the absence of append mode).

**Comment by GhoulofGSG9** [comment]
Sorry for the late input:

The crash occurs when reading a rather large file in one chunk. Because spark's lua memory allocator currently returns a null pointer when the allocation failed which is not the expected return value for a failure by the file read operation. The next game update is going to fix that.

Additional the next update will implement the append file mode. So you don't have to load in the complete file just to add some lines to the end ;)

Hope this helps.

**Comment by Rusty01** [comment]
https://github.com/Person8880/Shine/blob/44504a237791913b6dbb5227190569c97c443e24/lua/shine/core/server/logging.lua#L67-L86

**Comment by Rusty01** [comment]
We're still getting the red plugs, and really bad lag stutters. Would you mind reverting the last patch to Shine as I think it might fix whatever is causing it. I'm getting a lot of complaints :/ It's only started since Saturday. The crashing has stopped since I disabled logging but lag persists.

**Comment by Person8880** [comment]
> 
> 
> Sorry for the late input:
> 
> The crash occurs when reading a rather large file in one chunk. Because spark's lua memory allocator currently returns 0 (NULL) when the allocation failed which is not the expected return value for a failure by the file read operation. The next game update is going to fix that.
> 
> Additional the next update will implement the append file mode. So you don't have to read the complete file just to add some lines to the end ;)
> 
> Hope this helps.

Good to hear that append mode is finally going to be supported. I've sort-of worked around the issue for now until the next NS2 update (assuming 10MiB isn't too much to load into memory at once).

> 
> 
> We're still getting the red plugs, and really bad lag stutters(plug icon doesn't always show). Would you mind reverting the last patch to Shine as I think it might fix whatever is causing it. I'm getting a lot of complaints :/ It's only started since Saturday. The crashing has stopped since I disabled logging but lag persists. It's strange as everything was working very smooth i the past, so not sure what else it could be.. :/

As I mentioned before, the last update won't have caused this. It's possibly your very large user config, which I've just released some performance improvements for badge parsing which should help. I'd also suggest applying the master badge lookup to reduce the size of it as I imagine it's still going to take significant time just to parse the JSON in the first place which I can't do much about.

**Comment by Person8880** [comment]
I've just released some more changes that should mean that large JSON user configuration/web configuration being loaded mid-round won't cause the server to freeze up parsing it.

If you still have freezing issues after this update and you can see them occurring alongside something Shine is doing (e.g. reloading config), then feel free to re-open this issue.
