### ISSUE TITLE
[Feature Request] Map Vote - Approval Voting!

### ISSUE THREAD

**Issue by tkdavies525** [Person8880/Shine#809]
https://en.wikipedia.org/wiki/Approval_voting

Instead of voting for one map, you can vote for as many maps as you like (or is configured by the server), and the map with the most votes in the end wins. At the moment, people seem to suffer from mob mentality and will vote for whatever map the first person votes for. They can also only vote once.

Approval voting is the simplest voting system that doesn't have a "spoiler effect," where people who like both A and B split their vote between A and B causing both of them to lose. Instead of voting once for the thing you like, you can vote once for as many different things as you want. (You vote for all the options you "approve of," hence the name.) This wouldn’t require any changes to UI, the only change would be that when you vote for another map, it no longer undoes your previous vote. This would increase the diversity of maps that get played, by letting people who want “anything but veil” vote for several of the less played-maps instead of having to coordinate to pick one in order for it to have a shot.

This was suggested by moultano who is CDT and it's a great idea. Can you do it? :)

**Comment by Person8880** [comment]
I've implemented this in 6eacb579d438a8be20d759e5c4a8796e7e82e35f, which will be in the next update. Set `VotingMode` to `MULTIPLE_CHOICE` to enable approval voting, and use `MaxVoteChoicesPerPlayer` to limit the number of choices a player can make.
