### ISSUE TITLE
Suggestions for Map vote

### ISSUE THREAD

**Issue by Shrimm945** [Person8880/Shine#811]
Make it so that when you mouse over a maps preview image it overlays the minimap file so that people can see a map by it's layout.

Votes can be manipulated through a couple methods that should be fixed in my opinion. 

Allowing multiple votes and the ability to freely remove votes gives the player the opportunity to influence how a vote goes by removing votes from maps that are tied or close to tieing.

Showing what others voted for creates herd mentality, People will vote for whatever already has votes without even looking. 

Hiding votes until the voting is over ensures players are not being influenced by others this way, this also means people can't manipulate the multi-vote system.

Randomize the positions of each map client side so that everyone's maps are not in the same position, helping to mitigate for example, the top left map getting auto votes from people who just vote instantly.

If you want to get really fancy, with the votes hidden. Give voting a weight system, so players can give their 4 votes out freely to any map, even the same one multiple times. Votes on the same map from the same person would have diminishing returns so in example 1 vote counts for 1, 2 votes counts for 1.75, 3 votes counts for 2.375 votes, 4 counts for 2.5 votes. Maps would also have a multiplier based on how recently it was played, in example again, played 3 rounds ago multiply votes by 0.9, two maps ago multiply votes by 0.75, played last round multiply votes by 0.5

**Comment by Person8880** [comment]
The full screen map vote menu can already show map overviews on hover if you click the button at the top right of the tile (the world icon). Originally when developing it I had it appear on hover, but I changed it as it's a bit distracting and it can cause more hits to the overview API as people hover over mod tiles. The old map vote menu has displayed overviews on hover for a long time, and still does.

As for hiding vote counters, this has been requested previously in #711. My question from that issue still stands: I'm not sure I see the problem with players voting for what others do, ultimately they're still making a choice. People removing votes also isn't that much different to them not voting for the map in the first place. If a tie has influenced them to choose a preference then that's not necessarily a bad thing. I'm also not sure it's entirely down to seeing what others vote for, many players are quite vocal whenever a server cycles to a fairly unknown map, even if it won the previous vote. This causes people to either immediately vote to change again, or leave the server entirely. Hiding the vote counts to try to prevent popular maps from being played would expose this more often instead.

Randomising map positions is another thing I'm not sure is necessary. If someone is not invested in the map vote and just picks the top left tile, why would it be helpful to change what that tile means? Either way they've thrown their vote away. The maps are also already somewhat randomly chosen after exhausting forced maps, nominations and extending the current map.

Finally, for the weighting system, I think that's possibly overcomplicating things. Preventing previous maps from being played is already possible, and there's various existing map cycle options for controlling how often a map should be played (e.g. by limiting the percentage). Adding fractions to votes would also be hard to communicate, a result of `10.375/20.75` is quite jarring, and leaves players wondering what the weightings are and not able to understand their impact on it. Rounding it off would be effectively lying to players.
