### ISSUE TITLE
Add draw vote

### ISSUE THREAD

**Issue by Shrimm945** [Person8880/Shine#812]
Allow players to vote for the game to end in a draw. 

Default settings: disable the vote until the 20 minute mark, requires 90% of players to vote.

This basically gives players an out for the occasional game that is just never ending but noone wants to quit or surrender because they will lose elo, This says if both teams agree then hive will not tally this game so you can just move on to a new game already.

**Comment by Person8880** [comment]
This will be in the next update as the `votedraw` plugin. See the [wiki page](https://github.com/Person8880/Shine/wiki/Vote-Draw) for details.
