### ISSUE TITLE
Disallow spectators from taking part in votes during an active game.

### ISSUE THREAD

**Issue by Shrimm945** [Person8880/Shine#813]
Don't allow spectators to vote while a round is ongoing. It is mildly common to see votes swung by spectators who are only voting yes to try to get a spot in a game, Whether its a shuffle hoping someone leaves, or a map vote, or a kick, etc.

**Comment by Person8880** [comment]
All votes from plugins (map vote, shuffle, all talk) can already be blocked for spectators by setting `VoteSettings.ConsiderSpectatorsInVotes` to `false`.

Are you asking for this to be configurable to only apply during an active round? Or it just to be able to block spectators from starting/participating in vanilla votes?

**Comment by Shrimm945** [comment]
Yeah preferably only during an active round. also, would prefer for the default to be true, and allow server ops to opt out if they want.

**Comment by Person8880** [comment]
This will be in the next update as the `VoteSettings.ConsiderSpectatorsDuringActiveRound` option in the map vote, vote all talk and vote shuffle plugins, defaulting to `true` to preserve the existing behaviour.

Note that `VoteSettings.ConsiderSpectatorsInVotes` acts as a global toggle, with the new setting only applying if it's `true`.
