### ISSUE TITLE
Badges don't work on linux servers

### ISSUE THREAD

**Issue by snooops** [Person8880/Shine#814]
1st of all, Credits to Supafred to give me part's of his config of TTO to test this.

I'm creating a server for our awesome NSL team The Spectacular Gorges, and i'm having trouble enabling the NSL Badges of the EpsilonBadges Plugin.

OS: Linux Debian 64bit
Related enabled plugins:
Badges+
Shine/EpsilonBadges
Shine/Badges

You can view the complete config here: https://github.com/snooops/ns2-thespectaculargorges-config.

I guess this is related to the OS because it's working on Supafreds TTO running on Windows.

**Comment by snooops** [comment]
Yes i can approve this is a bug related to the operation system. I have tried my configuration from github on a windows server, and it worked, but on linux it don't. Maybe some stuff with filepaths or case-sensitive names.

**Comment by Person8880** [comment]
The epsilonbadges plugin grants access to badges named `ENSL#{ID}`, which looking in the Badges+ mod there is a badge file named `ui/badges/ENSL#1082.dds` which seems to be for your team.

The game itself searches the `ui/badges` folder for `.dds` files, taking the file name as the badge name. I'm guessing that's the part that's failing for you. If you run:
```
sh_luarun LuaPrint(rawget(gBadges,'ENSL#1082'))
```
in the server console, does it print a number, or `nil`?

**Comment by snooops** [comment]
sorry i get no output at all, what i'm doing wrogn?
`
Client connected (78.43.30.48)
[19:50:58]Client Authed. Steam ID: 433859
Wololooo connected.
sh^?^?
sh_luarun LuaPrint(rawget(gBadges,'ENSL#1082'))
;
sh_luarun LuaPrint(rawget(gBadges,'ENSL#1082'));
/sh_luarun LuaPrint(rawget(gBadges,'ENSL#1082'))
`

**Comment by Person8880** [comment]
The server console is very strange for NS2, I think it has a separate window for input that you have to press tab, then tilde to open. You should be able to run it from the console in-game if you grant yourself access to `sh_luarun`, which might be easier.

**Comment by snooops** [comment]
I tried on the server too, i have access to all commands, do i need to load a plugin to enable sh_luarun?

**Comment by Person8880** [comment]
It's part of `basecommands`. Looks like it's been disabled in `BaseCommands.json`. Need to set `DisableLuaRun` to `false`.

**Comment by snooops** [comment]
ok now it works. I can submit the command ingame and see the response in the server console 📦 
it prints the number: 138

**Comment by Person8880** [comment]
Hmm, so it does know the badge file exists. Not sure why it's not granting it then.

What output do you get if you run:
```
sh_luarun LuaPrint(GiveBadge(<your steam ID>, 'ENSL#1082', 1))
```
(replacing `<your steam ID>` with whatever your ID is).

**Comment by snooops** [comment]
138 again

**Comment by snooops** [comment]
ah sry didnt saw that wit the steam id

**Comment by snooops** [comment]
its true and i have the steam badge now

**Comment by Person8880** [comment]
OK, so my next guess is the problem is in the request to the ENSL API in the epsilonbadges plugin. Unfortunately it doesn't have any logging around the requests it sends, so we'll have to inspect it manually.

Can you get the output of:
```
sh_luarun PrintTable(Shine.PlayerInfoHub.ENSLData)
```

If it's working correctly it should have your team details, but presumably it'll be either empty or marked as failed.

**Comment by snooops** [comment]
btw, we can meet on Discord if you want to ;)
```
table: 0x7e8ce140 {
        [ 433859 ] = 0
}
```

**Comment by Person8880** [comment]
That's the output I expected. The request managed to receive a response, but it's not valid so it's marked it as failed.

I assume it's a difference in the way the Linux and Windows servers are set to handle redirects, as the epsilonbadges plugin is hitting the ENSL website with plain `http` which redirects to `https`. Changing the code to use the `https` endpoint may fix it, but you'll need to raise it with the author of the plugin here: https://github.com/GhoulofGSG9/Shine-Epsilon/issues

**Comment by snooops** [comment]
Thank you alot, i will check it and let you know here.

**Comment by snooops** [comment]
It was because i didn't launched the server from the x64 directory ;)
