### ISSUE TITLE
Shine Revision 319 - Issues with Extra IP's plugin

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#816]
Hey. Since the shine version 319 we no are no longer able to spawn extra ip's with the shine plugin. There are no errors in the logs, it says it's loaded successfully but nothing happens. The .json is also correct/ hasn't been edited.

**Comment by Person8880** [comment]
I've just released a small update that should fix this. The plugin was relying on old behaviour which changed in the last update which I have partially restored.

**Comment by Wooza42** [comment]
thank you for the prompt fix! It worked
