### ISSUE TITLE
Request - Custom badge title when hovering over them

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#819]
Hey,

I would like the ability to give certain custom badges a title so when hovering over them it doesn't say "Custom Badge" but the title I defined (optimally in the userconfig.json or any file). 

The reason for this is that I have for example "troll badges", "stacker badges" and "event badges" which are just displayed as custom badge but I would like that there is more info on them when hovering over them.

Best regards

**Comment by Person8880** [comment]
The next update adds a `BadgeNames` option to the badges plugin configuration where you can specify names for badges. See the [wiki page](https://github.com/Person8880/Shine/wiki/Badges#config) for details.

**Comment by Wooza42** [comment]
Thank you a lot
