### ISSUE TITLE
Allow voterandom for Combat, Siege and GunGame

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#823]
Overall why is the voterandom plugin limited to mvm and ns2?

Is it not compatible?

**Comment by Person8880** [comment]
It may be compatible, but I've not tested it, and certain things like team preferences make no sense for gamemodes like GunGame.

Gamemodes can override the default compatibility checks using the `CanPluginLoad` hook (in #728 this was discussed for Combat and looks [to have been implemented](https://github.com/GhoulofGSG9/NS2Combat/blob/master/output/lua/Combat/FileHooks/Post/shine/core/shared/hook.lua)).
