### ISSUE TITLE
Shine .json file corrupt after a hardware crash

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#828]
Hey person. It's probably more of an informative message, I don't think it can be fixed or takes a lot of time but following:

Rarely when my server crashes (mostly due to overclock instability) it corrupts sometimes the BaseConfig.json file. Rarely also .json's from the plugin folder. I assume due them being in the memory / able to be edited by the game etc. the file gets corrupted.

Thanks for keep maintaining Shine.

Also if you have not known; me and the ns2 community often hangs out in the official ns2 server on Discord. It's a cozy place and you are welcome to join: https://discord.gg/UyzfF4H

**Comment by Person8880** [comment]
There was a small oversight causing the base config to be saved every time a new map loads even if nothing needed updating. That should no longer happen in the next update which will hopefully help.

Unfortunately I can't make the file saving mechanism any safer as the game lacks the ability to rename and delete files from Lua. Saving a file wipes the old contents and then writes the new data, which may end up half-flushed to disk in the event of a crash mid-write.
