### ISSUE TITLE
Build b335 on the way, with per-team-skill and other goodies

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#830]
Hey Person8880

I just want to let you know (probably you know already) that NS2 soon releases a new build containing per-team-skill and commander skill. The build is available on the beta branch for modders to check it out.

I think it's kinda important that shine works in combination with the new Hive3 since every server that uses shine also uses Shuffle and having a broken shuffle probably would not be great for release day of the build.

Thanks a lot for keep maintaining Shine. I wish I have the possibility to send you a cake, flowers or anything really.

**Comment by Person8880** [comment]
I've added support for team-based and commander skill values to shuffle for the next update (see the [new `BalanceModeConfig` option](https://github.com/Person8880/Shine/wiki/Vote-Random#config)). They're enabled by default as hopefully they should be an improvement over the old "average" value. One thing to note is that commander skill values are used on the assumption that the player commanding at the time of the shuffle will stay commander. So players hopping out of the chair after a shuffle will cause the team balance to be disrupted.

I've also fixed some other issues I could find with the chat positioning. Nothing else seems to be broken, so hopefully I've caught everything.

I'll probably release these changes tomorrow (they're backwards compatible with 334) so whenever 335 comes out things should work without issue.
