### ISSUE TITLE
New commander bot feature is incompatible with Enforce Team Size plugin

### ISSUE THREAD

**Issue by ironhorse86** [Person8880/Shine#835]
Since I cannot open an issue ticket with the Enforce Team Size plugin by ghoul (I did message him however) I am opening one here just so that you are aware at a minimum, considering the severity of this bug.

The new auto add bot commander feature combined with Enforce Team Size plugin enabled, will create a deadlock scenario where the round cannot start, because the bot commander is not allowed to join a team when the teams are full. And since players are often locked to the team / forbidden from going back to RR and they cannot replace the bot commander because he is not technically on a team yet outside of RR.. things remain in a deadlock. 
The only solution in that moment is for a player to disconnect from the server to allow the stuck commander bot to join the team so that they can then be replaced.

Disabling this plugin for the time being and then restarting the server resolves this issue.
It seems that while the Json file for this plugin has a field for ignoring bots, it is not taking into commander bots. 

Thanks and take care :)

**Comment by Squirrelies** [comment]
https://github.com/GhoulofGSG9/Shine-Epsilon/blob/master/lua/shine/extensions/enforceteamsizes.lua

Shine Epsilon by Ghoul is the package that contains Enforce Team Sizes plugin.

**Comment by Person8880** [comment]
It looks like Ghoul has [updated the enforce team sizes plugin](https://github.com/GhoulofGSG9/Shine-Epsilon/commit/fc747a47df2f277157cfc03ec41a0afe70e8da78) to fix the issue.
