### ISSUE TITLE
New feature BFF (Best Friends Forever)

### ISSUE THREAD

**Issue by Fredrik81** [Person8880/Shine#838]
At the moment friend groups die at map change. So each map you need to join up in the group.
This is very annoying if you are playing with a firend. It would be so nice to have a BFF :-) option to keep the group cross-map changes. And if you want you can always leave the group at any time so no harm in having one..

```
   ad88            88                                 88            
  d8"              ""                                 88            
  88                                                  88            
MM88MMM 8b,dPPYba, 88  ,adPPYba, 8b,dPPYba,   ,adPPYb,88 ,adPPYba,  
  88    88P'   "Y8 88 a8P_____88 88P'   `"8a a8"    `Y88 I8[    ""  
  88    88         88 8PP""""""" 88       88 8b       88  `"Y8ba,   
  88    88         88 "8b,   ,aa 88       88 "8a,   ,d88 aa    ]8I  
  88    88         88  `"Ybbd8"' 88       88  `"8bbdP"Y8 `"YbbdP"'  
 ```

**Comment by Person8880** [comment]
Friend groups will be restored after each map change in the next update (local to a given server). How long after a map change before stopping the restoration can be configured using the `TeamPreferences.FriendGroupRestoreTimeoutSeconds` option (default is 5 minutes which should plenty of time for people to load in, setting it to `0` disables restoring groups).
