### ISSUE TITLE
Please rework shuffle, or add an additional shuffle option.

### ISSUE THREAD

**Issue by Shrimm945** [Person8880/Shine#841]
The current shuffle results in stomps far too often. I'm asking to either change it to the way captains games work, or add an additional option for server ops to choose to enable.

In case you don't know how it works, captains shuffle is a round robin style where it simply picks the highest skill player back and forth until both teams are full. This results in wonky team averages, but better games and "lane averages", Team average falsely assumes everyone will be in the same place on the map. Most maps have 3 lanes that split the team.

Please review this spreadsheet that goes over why a captains style shuffle is better for NS2.

https://docs.google.com/spreadsheets/d/1SAOIicx0Uux_547rdwLbvoUZiqu3EGmIwnOsEIvyZRE/edit?usp=sharing

**Comment by Person8880** [comment]
I'm not sure how you got your output for what you believe shuffle is doing, but it's not the actual result. Here's a result of applying shuffle to the teams in your spreadsheet:

Team 1 | Team 2
-------- | --------
4256 | 4312
3342 | 2542
2331 | 2532
2231 | 2342
2212 | 2309
2209 | 2287
1835 | 2231
1522 | 1922
1333 | 1023
1232 | 1012

Note how it's very similar to your captains shuffle result, but it's accounted for standard deviation and thus arguably the lanes are actually better here.

A few things to note:
* Shuffle is not deterministic, it randomises the starting players and thus can end up with slightly different results (as hill climb optimisation can hit local minimums).
* The current method also trivially accounts for team preference and friend groups. Your suggested method would not.
