### ISSUE TITLE
Issuing shine commands from sh_adminmenu while commanding triggers infinite error loop

### ISSUE THREAD

**Issue by Telemancer** [Person8880/Shine#843]
For me this is reproducible 100% of the time, but dont know if its an issue specific to my server or client settings. Issuing any shine command using the adminmenu gui while you are alien or marine commander, even during pregame, triggers an infinite error loop client side. The commander menu becomes disabled and error loop continues until you log out of the chair/hive.

The commands you issue still execute, the error is seemingly with the gui. The error is only client side. ( I know cause I operate the server). And only if using the sh_adminmenu. Regular commands or chat commands using ! do not trigger the error.

log attached, let me know if I can help in any other way.
[error.txt](https://github.com/Person8880/Shine/files/5720248/error.txt)

**Comment by Person8880** [comment]
This will be fixed in the next update, thanks for reporting.
