### ISSUE TITLE
getting "nil" errors.

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#846]
Hi, since the last update, we've been seeing this appear in our server logs. I don't think it's a big deal but wanted to mention it as it does create a lot of spam. Thanks.

![Capture](https://user-images.githubusercontent.com/12983350/109532943-ab6aaa00-7a87-11eb-844f-8cee65d7479f.JPG)

**Comment by Person8880** [comment]
Is the server running a custom gamemode? Do these plugin config files actually exist and contain valid JSON?

**Comment by Rusty01** [comment]
Hi, yes the server us running the Combat gamemode. The files exist and are valid and functioning.

**Comment by Person8880** [comment]
There's an issue with how config file loading errors are reported when either:
* The file exists but reading it fails.
* No file exists when using a custom gamemode (as it checks for a gamemode specific file, then the default file).
* The file contains valid JSON, but it's not an object (i.e. the first character isn't `{`).

I can improve the error messages, but the errors you're seeing means one of the above is wrong with your current configuration files.

**Comment by Person8880** [comment]
I've just released an update that should improve the error message you're seeing to better explain what's wrong with the config.
