### ISSUE TITLE
Servers not pulling from web

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#854]
Heya, not sure if it's a problem on my end, but my userConfig.json isn't pulling from web and updating. My config is setup correctly. I haven't touched it in some time. There's no json errors. Any ideas?
Thanks!

**Comment by Rusty01** [comment]
Actually this is weird. So I copied my userConfig.json over from the web to the server and did sh_reloadusers. It didn't update. I had to change the map to get it to update. (however even after a server restart the userConfig.json would not pull from the web. I had to copy it to the servers shine folder.

**Comment by Person8880** [comment]
Do you have server logs from the time you tested this (or any time since this issue started)? There should be log messages if an error occurs when loading the data, or if it succeeds.

**Comment by Rusty01** [comment]
Yes, it says.
"[23:58:29]All attempts to load users from the web failed. Using local file instead."
There's nothing else about it in the log.

**Comment by Person8880** [comment]
That implies the request is timing out on each attempt. The timeout time is 5 seconds, does your web server usually respond in less than that? It could also be that for some reason the server running NS2 can't reach your web server (e.g. DNS issues or some routing failure).

Unfortunately the game's HTTP request system doesn't really provide any useful error information, so it's hard to know what exactly is causing the request to fail.

**Comment by Rusty01** [comment]
Ok thanks, I'll move it to another host and see what happens. It fails on
all 6 servers so could be the web host. The only thing I changed on the web
host was adding a dedicated IP address.

**Comment by Rusty01** [comment]
Wanted to update. I changed the host and it worked ok. I am wondering why it wouldn't work on the original host. Do you think it's a port issue?

**Comment by Person8880** [comment]
There could be many different issues that would cause it, without knowing the details of a given web host and seeing any logs it has it's not really possible to know for certain.

Given it works on another host there must have been some misconfiguration on the original host.

**Comment by Person8880** [comment]
Turns out the game does expose error messages, just they were never used by the vanilla code until recently so I didn't know they were available. I've just released an update that uses these so if this happens again it should hopefully be easier to diagnose.
