### ISSUE TITLE
Reserved Slots not hiding on server browser

### ISSUE THREAD

**Issue by paulrjbagnall** [Person8880/Shine#855]
Currently set to 1 slot, all and take instantly, however, doesn't remove the slot from the listing. Tried on current and a fresh server too.

**Comment by Person8880** [comment]
The reserved slot system used by the browser only works on player slots, which means if your reserved slots cover only spectator slots the browser won't know about it.

**Comment by paulrjbagnall** [comment]
So i just set it to 'Playable' ? 

Thx for the quick reply.

**Comment by Person8880** [comment]
That depends on how you want it to work. If you set it to playable, then the server can't fill up to its maximum player count without at least one player that has reserved slot access (and this will be visible in the browser as a reduced player count).

If you just want to reserve spectator slots, then there's unfortunately no way to get the server browser to be aware of it at the moment.

**Comment by paulrjbagnall** [comment]
I've set it to 21 slots with one hidden, Max team sizes of 10 v 10. That should work right? Or will one player always be able to get into the readyroom?

Is there a better way of doing it? I just need to make sure one player can join at any point.

**Comment by Person8880** [comment]
Only a player with reserved slot access will be able to get into the ready room in that final slot. As long as the team sizes are enforced then yes, that should maintain 10v10 and until a reserved slot player joins the browser should show the server with a limit of 20 players.
