### ISSUE TITLE
UI bug: GUI skin selection menu stucks on screen

### ISSUE THREAD

**Issue by Aazuu** [Person8880/Shine#856]
Reproduce steps:

Go:
Mods - Shine Options - Open Client Config Menu -> Drop down GUI skin selection menu -> Press ESC

Skin selection drop down menu stays on screen (picture), even tho Client Config Menu is gone.

**Comment by Aazuu** [comment]
![client config menu ui bug](https://user-images.githubusercontent.com/88404584/128081579-e11ddcf5-e5f3-494a-b6f1-a69a24324456.jpg)

**Comment by Person8880** [comment]
This should be fixed in the next update, thanks for reporting. In the meantime, you should be able to get rid of it by re-opening the config menu and clicking the dropdown again.
