### ISSUE TITLE
infested mod, voting for same map again but no infested bugs

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#860]
Players vote for `infest_veil`, server loads `ns2_veil` with infested mod automatically; players at the end of the map, vote for `ns2_veil`, server gets confused and bugs it seems.
The extend vote, extends `ns2_veil`, instead of `infest_veil` and well at times it possible to extend ns2_veil, and vote for ns2_veil twice.

So due to how ns2 vanilla manages the `infest_` prefix .. it makes problems. The code is in core/lua/MapCycle.lua *line 108 -> HasPrefix

**Comment by Person8880** [comment]
I've updated the plugin to identify that it's loaded `infest_<map>` if:
* There's a map cycle entry for `infest_<map>`.
* The currently active mods include the infested mod (as defined in the game code).
* The current map is `ns2_<map>`.

This allows for extending the infested map as expected (along with properly loading map-specific settings for it and knowing where it is in the cycle), and will be in the next update.
