### ISSUE TITLE
infested mod, mapvote preview pics

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#861]
It would be nice if the mapvote plugin could just overlay the existing map preview picture the following: 
(currently it does not even load the original preriew picture, probably cause of the altered map name)

![overlay-infested](https://user-images.githubusercontent.com/1570625/135710492-05cdf551-18ed-4703-aa1c-566d76d02967.png)

**Comment by Person8880** [comment]
I've added this as an overlay for any map with the `infest_` prefix in the next update (as well as adding "Infested:" before the map name rather than "Infest").
