### ISSUE TITLE
Feature request: go spectator before map change

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#863]
Not 100% sure this is controlled by Shine but I think so. Currently players can't go spectator during the time between round end and map change. I can't see any reason for this and would like this to be changed.

Spectator slots are used on most servers as a way for people to queue for a player slot (using the plugin readyroomqueue in the Epsilon mod). The queue feature is a bit buggy and especially so just after a map change which means that players in the queue sometimes aren't moved to the rr and players who just joined the server get the slot instead. By allowing players to join the spectators before map change (during a period where the queue mod works) more players who have been waiting a long time in the queue will get player slots.

Thanks again for all your work on this mod!

**Comment by Person8880** [comment]
I've updated the map vote plugin to no longer block going into spectate mode during the end of map vote/cycling phase. This change will be in the next update.
