### ISSUE TITLE
Bug? Custom welcome messages not displayed

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#865]
If a player has a custom welcome message in WelcomeMessages.json it is not displayed after a map change. The default message is shown for other players but nothing is shown for the ones with custom messages.

**Comment by Person8880** [comment]
The plugin tracks whether a custom message has been displayed for a player across map changes but not generic messages. I've changed it in the next update to track both, which means after a map change there will only be connection messages for players that weren't previously connected.
