### ISSUE TITLE
issue with mapcycle.json

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#867]
Hi, hope you're doing well.
Could you do me a favour and take a peak at my Mapcycle.json?
I was using this before the latest update from hexadecimal to decimal modids.
but if I try and use it, the mapvote plugin disables with the following error
`[02:00:44][Map Vote] [Error] The map cycle "maps" list is invalid (expected table, got nil). Check the MapCycle.json file`
The Mapcycle.json looks correct, but would you mind giving it a once over to see what I'm missing?
I like being able to use the // comments for notes as it's easier to enable / disable mods this way.
https://pastebin.com/gxmBivim

Thanks!

**Comment by Person8880** [comment]
You should see somewhere in the main log file a line like:
```
Error while opening MapCycle.json:
```
From what I can see you have an unquoted hex value in the "mods" list on line 66 which isn't valid JSON.

**Comment by Rusty01** [comment]
Yup, that'll do it. Thanks!
