### ISSUE TITLE
Error in pulling users from web.

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#871]
Hi Person8880, Happy New Year!
Since the game was last updated, I've been unable to pull the users from the web. Hoping you can help me with this. 
The log file shows this error.
[10:33:47]Loading from the web failed. Using local file instead. Error: no valid JSON value at line 1, column 1
Here's my userConfig.json. _The file works if I copy it over to the servers userConfig.json_

It was working prior to the latest update.

https://pastebin.com/1QHtSFG1
As always, thank you for your dedication to the Shine project, and Thanks for your help! :)

**Comment by Person8880** [comment]
Can you check what response your web server is giving? It might be returning an error page instead of the user data.

**Comment by Rusty01** [comment]
I think I found the issue, you led me to the right place. It looks like
some web based control panel for another game I host was interfering. I
need to check those configs to see why this occurred. Thanks for your help.
