### ISSUE TITLE
Error on server startup: PluginTable

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#874]
Hi, 

Just going over my server logs and I see this in the servers log file right after all the mods load. 
Is this error being generated due to a bad plugin?

[02:53:02]Loading Shine config...
[  2.297] Worker 00 : Error: lua/shine/core/server/config.lua:413: attempt to index local 'PluginTable' (a nil value)
[  2.297] Worker 00 : Error: invalid key to 'next'
[  2.297] Worker 00 : Error: invalid key to 'next'
[  2.297] Worker 00 : Error: invalid key to 'next'
(repeats)

Thanks.

**Comment by Rusty01** [comment]
Oh looks like that's not the case. I just disabled my baseConfig.json, restarted the server so it would generate a new one and am getting the same error.

**Comment by Rusty01** [comment]
aah never mind, found the culprit. It was a bad shine plugin, One of my guys updated our Captains mod and it had an error. He failed to tell me. My servers were crashing on startup. I removed the mod and the shine error went away, and server started w/o issue. I'll leave this info here for reference. Thanks. Hope you have a great weekend! :)

**Comment by Person8880** [comment]
Looks like this would happen specifically for a plugin not yet configured in `BaseConfig.json` which also fails to register itself. Should be fixed by 833ba96dc38cdc32342e4a1755806907d43e86cc.
