### ISSUE TITLE
Pregame Plugin

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#875]
Hi Person8880.

Quick question for you.
I have pregame set to "one commander" which is great for seeding.
The problem is however when the server is full there is no way to turn that off.

The config has a setting to configure the Min player count but not a max player count.
So the issue we face is when a server is full, map changes, and the game starts prematurely often before there are two commanders.
Is there a way to disable the plugin if there are X amount of people on the server?
It would be great if there was a way to disable the "one commander" start if there are more than X players on the server.
The time variables don't help as it can at times take 5 mins before people decide to stop chatting and actually find commanders.
Thanks

**Comment by Person8880** [comment]
I've added a `MaxPlayers` option in bdaa3927e09cd00b22b847fd2d1a24a94d609ac7 that will revert to the vanilla starting rules if the number of players exceeds the given value.

**Comment by Rusty01** [comment]
You are simply amazing! Whoever you work for is lucky to have you!
Thank you so much!

**Comment by SupaFred** [comment]
+1 from me. Thanks a lot, I’ll use this on The Thirsty Onos too.

Fred

**Comment by Person8880** [comment]
I did wonder if that would be an issue, it looked at players on teams simply because that matched the behaviour of the `MinPlayers` option. However, it makes more sense for it to use the number of players on the server so I've changed it to do so for the next update.
