### ISSUE TITLE
Bots are shuffled to a team

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#877]
Since I configured my server to automatically shuffle the teams on round start bots have started being shuffled onto a team even when the server is full and there are no bots on the server. 

After a shuffle the teams can look like this https://www.dropbox.com/s/741pys6t3ucem5c/20220612202127_1.jpg?dl=1
It might be afk players that are left in the readyroom but I haven't confirmed that yet. A reset (and new auto shuffle) always fixes the problem.

For reference here is a recent log with debugging enabled for shuffle:  https://pastebin.com/4B4ywWU4
Here is my config for the plugin VoteRandom: https://pastebin.com/AbP6tBiz

I would really appreciate if you could take a look at this. Thanks!

**Comment by Person8880** [comment]
My initial impression is that you're ending up in a situation where:
* Bots exist on the teams as not enough players have joined them, but there are enough players to entirely fill the teams on the server.
* The shuffle process constructs the new teams, but given the configuration has `ApplyToBots` set to `true`, it includes the bots on the empty teams in the shuffle process and thus ends up with team sizes that are larger than allowed.
* When the constructed teams are assigned, the bots use up spaces on the teams and players get prevented from joining by the team size limits. The bot controller is blocked from running during this time so it doesn't have a chance to remove the bots that are no longer needed.
* Teams are now full, so no further team changes are possible and thus the bot controller doesn't update the teams until there's another change (e.g. someone moves to ready room, or you reset the game).

I can fix the logic in this case to automatically remove bots if they exceed the team size limits, though in the meantime you can also set `ApplyToBots` to `false` to make bots get removed when a shuffle occurs. The caveat to this is that they'll be removed even if they're needed to fill the teams, though as soon as any team change occurs the bot controller will pick it up and add them back again providing `BlockBotsAfterShuffle` is `false`.

**Comment by SupaFred** [comment]
I have tried the workaround you suggested for a few days now and that fixed the problem for me. I think it would be good to change the logic though since I guess that most (all?) server ops would want to shuffle players onto teams before bots if a servers player slots are full. 
Thanks a lot!

**Comment by Person8880** [comment]
This should be fixed in the next update.

**Comment by SupaFred** [comment]
Thanks! It seems like the fix is only partially working though. Here's a log from last night where one bot got removed and one bot got to stay on a team.
https://pastebin.com/aBz6tWPZ

**Comment by SupaFred** [comment]
I'll test this a little bit more :)
