### ISSUE TITLE
!enablecombots command cause infinite loop of adding comm bots after a round

### ISSUE THREAD

**Issue by Hitman4** [Person8880/Shine#879]
i used !enablecombots true true and after one round i got timed out
[log-Server-24-08-2022.txt](https://github.com/Person8880/Shine/files/9428147/log-Server-24-08-2022.txt)

**Comment by Person8880** [comment]
That's a command from the [Epsilon](https://github.com/GhoulofGSG9/Shine-Epsilon) mod, so you'll need to raise the issue there instead.
